// System version log — shown to all signed-in users (upgrade report since v1).
export interface VersionEntry {
  version: string;
  date: string; // YYYY-MM-DD
  by: string; // author (GitHub: lklfred = Fred Li)
  titleEn: string;
  titleCn: string;
  itemsEn: string[];
  itemsCn: string[];
}

export const CURRENT_VERSION = "4.7";

export const VERSIONS: VersionEntry[] = [
  {
    version: "4.7",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Two-layer regions & interactive star map",
    titleCn: "两层地区分类与可交互星图",
    itemsEn: [
      "Regions now follow a best-practice two-layer model — broad macro-regions (Greater China, Southeast Asia, Northeast Asia, South Asia, Global) each grouping the specific territories, so Southeast Asia correctly includes Singapore, Malaysia, Indonesia, Vietnam and the Philippines",
      "Renamed the old 'International' bucket to 'Global' for anything that cannot be placed in a specific region",
      "The region filter and the star map are now mutually linked — click a region hub on the map to filter to it, and it highlights in gold; clear it and both update together",
      "Fixed a scroll bug where long people-picker lists were cut off at the bottom of the screen on smaller devices",
    ],
    itemsCn: [
      "地区采用最佳实践的两层分类 — 宏观大区（大中华区、东南亚、东北亚、南亚、全球）分别统领具体地区，东南亚现已正确包含新加坡、马来西亚、印尼、越南与菲律宾",
      "将原来的“国际”归类重命名为“全球”，用于无法归入具体地区的伙伴",
      "地区筛选与星图现已双向联动 — 在星图上点击地区节点即可筛选并以金色高亮，取消时两者同步更新",
      "修复在较小屏幕上选择负责人时长列表被屏幕底部截断、无法滚动的问题",
    ],
  },
  {
    version: "4.6",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Updates tabs & smoother rights editing",
    titleCn: "动态双日志与更顺手的权限编辑",
    itemsEn: [
      "Updates page split into two tabs — the system update log (every release, newest first) and a new partnership records log that lists every partner by date, newest first",
      "Admin rights matrix now stages your changes — tick the boxes (they highlight instantly) and save the whole row in one go, instead of a slow save on every click, with a Reset to discard unsaved edits",
      "Removed the duplicate internal-testing note in the bottom corner",
    ],
    itemsCn: [
      "动态页拆分为两个标签 — 系统更新日志（每次发布，最新在前）与全新的合作记录日志（按日期列出每家合作伙伴，最新在前）",
      "管理后台权限矩阵改为暂存式编辑 — 勾选后立即高亮，整行一次性保存，不再每次点击都缓慢保存，并可一键重置放弃未保存的更改",
      "移除右下角重复的内部测试提示",
    ],
  },
  {
    version: "4.5",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Desert scene, R&D planner, display options & rights matrix",
    titleCn: "沙漠场景、研发规划、显示选项与权限矩阵",
    itemsEn: [
      "New Developer R&D Planner — dev/admin-only roadmap of the ecosystem's modules, functions and agents on a date timeline with teammate tags, built to show management",
      "Light mode now opens onto a cinematic Gobi desert — drifting dunes, wind-blown sand and a slow camel caravan with long shadows; dark mode keeps the galaxy",
      "Display options on cards and the star map — toggle NEW, LP star, PIC, region, stage and category blocks before screenshotting as a slide",
      "Admin accounts redesigned as a rights checkbox matrix (View / Edit / IR / Dev / Admin) with a plain-language legend, including the new Developer tag",
      "Admins can edit any member's name, title and photo, and run the gobi.vc sync for them",
      "Roles and network synced from fred-li.vercel.app — updated title and nine new ecosystem partners across HK universities, NUS BLOCK71, BIOCHINA, Tencent Education, RITS, GBA NTIC and LEAP East",
      "Related sites in the footer (gobi.vc and fred-li.vercel.app), and the update log now shows the author of each release",
    ],
    itemsCn: [
      "新增开发者研发规划 — 仅开发者与管理员可见，以时间线展示生态内模块、功能与智能体的建设计划，带团队成员标签，可直接向管理层展示",
      "浅色模式呈现电影感戈壁沙漠 — 沙丘漂移、风沙拂过、驼队缓行并投下长影；深色模式保留星空",
      "卡片与星图新增显示选项 — 截图做幻灯片前可自由隐藏 NEW、LP 星标、负责人、地区、阶段与类别信息块",
      "管理后台账号改为权限勾选矩阵（查看 / 编辑 / IR / 开发 / 管理），含新增的开发者标签，并附通俗易懂的权限说明",
      "管理员可编辑任何成员的姓名、职位与照片，并可代为执行 gobi.vc 同步",
      "角色与网络与 fred-li.vercel.app 同步 — 更新职位，并新增九家生态伙伴（香港高校、NUS BLOCK71、BIOCHINA、腾讯教育、深圳清华研究院、大湾区国创中心、LEAP East）",
      "页脚新增相关网站（gobi.vc 与 fred-li.vercel.app），系统更新日志显示每次发布的作者",
    ],
  },
  {
    version: "4.4",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Galaxy interface",
    titleCn: "星系界面",
    itemsEn: [
      "Animated starry-galaxy background across the portal, including the sign-in screen — twinkling stars, drifting nebulas and the occasional shooting star",
      "Glass interface — cards, dialogs and panels are now slightly translucent with a soft blur so the galaxy shows through",
      "Adapts to light and dark mode, and respects reduced-motion system settings",
    ],
    itemsCn: [
      "全站动态星空背景（含登录页）— 星光闪烁、星云漂移，偶有流星划过",
      "玻璃质感界面 — 卡片、弹窗与面板微透明并带柔和模糊，星空若隐若现",
      "自适应深浅色模式，并遵循系统的减少动效设置",
    ],
  },
  {
    version: "4.3",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "LP status, smarter AI intake & data upgrade",
    titleCn: "LP 状态、更智能的 AI 录入与数据升级",
    itemsEn: [
      "Remember me — stay signed in on this device between visits",
      "One-click profile sync from gobi.vc (photo and title) after registering",
      "Smarter AI intake — detects documents, links or plain text, fetches linked pages, summarises the relationship and suggests the PIC automatically",
      "LP status per partner (N/A / Target LP / LP) — visible only to the IR team, with a new IR-team toggle in admin accounts",
      "Full partnership info upgrade — researched descriptions, PICs, start dates and LP flags across the directory, sourced from gobi.vc and public news",
      "New Advisors section (coming soon) and a portal-wide disclaimer in the footer",
    ],
    itemsCn: [
      "记住我 — 在本设备上保持登录状态",
      "注册后可一键从 gobi.vc 同步个人资料（照片与职位）",
      "更智能的 AI 录入 — 自动识别文档、链接或纯文本，拓展链接内容，总结合作关系并自动建议负责人",
      "合作伙伴 LP 状态（无 / 目标 LP / LP）— 仅 IR 团队可见，管理后台新增 IR 团队开关",
      "合作信息全面升级 — 基于 gobi.vc 与公开报道补充描述、负责人、起始日期与 LP 标识",
      "新增顾问板块（即将上线），并在页脚添加免责声明",
    ],
  },
  {
    version: "4.2",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Filters, feedback & photo galleries",
    titleCn: "筛选、反馈与照片展示",
    itemsEn: [
      "Filters now support selecting multiple options at once (category, stage, region, year)",
      "New Updates page — full system update log plus system requests & feedback",
      "Submit a system request from the portal and track its status (open / in progress / solved / declined)",
      "Admins can reply to requests, manage them in a new admin tab, and add team accounts directly",
      "Search boxes added to the admin console (partnership records and team accounts)",
      "Partner photo carousels — example galleries added for HKU, HKUST and HKIC",
    ],
    itemsCn: [
      "筛选器支持多选（类别、阶段、地区、年份）",
      "新增系统动态页面 — 完整更新日志与系统需求反馈",
      "可在门户内提交系统需求并跟踪处理状态（待处理 / 处理中 / 已解决 / 已拒绝）",
      "管理员可回复需求、在新的管理页签中处理，并可直接新增团队账户",
      "管理后台新增搜索框（合作记录与团队账户）",
      "合作伙伴照片轮播 — 已为港大、科大与港投公司添加示例图库",
    ],
  },
  {
    version: "4.1",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Account security & email",
    titleCn: "账户安全与邮件",
    itemsEn: [
      "Forgot password — reset via an emailed link or by answering secret questions",
      "Secret questions are set during registration (bilingual, answers stored hashed)",
      "Confirmation email sent when registration completes",
      "@gobi.vc registrations are approved automatically as viewers — sign in right away",
    ],
    itemsCn: [
      "忘记密码 — 可通过邮箱重置链接或回答密保问题重置",
      "注册时设置密保问题（中英双语，答案加密存储）",
      "注册完成后自动发送确认邮件",
      "@gobi.vc 邮箱注册自动获批为查看者，无需等待审批",
    ],
  },
  {
    version: "4.0",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Login-first, Gobi rebrand, timeline & audit",
    titleCn: "登录优先、Gobi 品牌升级、时间线与审计",
    itemsEn: [
      "Sign-in is now required before viewing any content",
      "Rebranded to Gobi Partners with the official logo (light/dark)",
      "Partnership stage (01-05) and collaboration level merged — stage is the single source of truth",
      "New timeline view with date-range and year filters",
      "Hall of Fame is now a mode inside the star map, with full filters",
      "Export records to Excel or CSV with selectable fields",
      "Start date is compulsory; AI quick-fill estimates it from documents",
      "AI quick-fill now runs on DeepSeek (PDF / DOCX / text)",
      "NEW badge on entries added within the last month",
      "Lists sorted by strategic level, then alphabetically",
      "Per-partner change log (who changed what, when) for audit",
      "Editable user profiles — title and photo",
      "Edit button in partner details for signed-in staff and admins",
      "Admin table shows PIC and start date columns",
    ],
    itemsCn: [
      "查看任何内容前必须先登录",
      "品牌升级为 Gobi Partners，启用官方标识（明暗两版）",
      "合作阶段（01-05）与协作等级合并 — 以阶段为唯一标准",
      "新增时间线视图，支持日期区间与年份筛选",
      "荣誉殿堂并入星图模式，支持全部筛选条件",
      "支持导出 Excel 或 CSV，可自选字段",
      "开始日期为必填项；AI 速填可从文档中估算",
      "AI 速填改用 DeepSeek（支持 PDF / DOCX / 文本）",
      "近一个月新增条目显示 NEW 标识",
      "列表按战略等级排序，再按字母排序",
      "每个伙伴均有变更记录（谁、何时、改了什么）以供审计",
      "用户可编辑个人资料 — 职位与照片",
      "登录后可在伙伴详情中直接编辑",
      "管理表新增负责人与开始日期列",
    ],
  },
  {
    version: "3.0",
    date: "2026-07-12",
    by: "Fred Li",
    titleEn: "Full partner sync, star map & multi-PIC",
    titleCn: "全量伙伴同步、星图与多负责人",
    itemsEn: [
      "Synchronised the full 55-partner database",
      "Interactive star map (network view) of the partnership ecosystem",
      "Multiple Gobi PICs per partnership with avatar groups",
      "Developer note and internal-testing banner",
    ],
    itemsCn: [
      "同步全部 55 家合作伙伴数据库",
      "合作生态互动星图（网络视图）",
      "每个合作可指定多位戈壁负责人，头像组展示",
      "开发者署名与内部测试横幅",
    ],
  },
  {
    version: "2.0",
    date: "2026-07-10",
    by: "Fred Li",
    titleEn: "Roles, AI quick-fill & attachments",
    titleCn: "角色权限、AI 速填与附件",
    itemsEn: [
      "Admin / staff / viewer roles with approval workflow",
      "AI quick-fill: paste text or upload documents to fill the form",
      "File attachments on partnership records",
      "01-05 partnership stage pipeline",
    ],
    itemsCn: [
      "管理员 / 员工 / 访客角色与审批流程",
      "AI 速填：粘贴文本或上传文档自动填表",
      "合作记录支持文件附件",
      "01-05 合作阶段管道",
    ],
  },
  {
    version: "1.0",
    date: "2026-07-08",
    by: "Fred Li",
    titleEn: "First release — bilingual partnership portal",
    titleCn: "首个版本 — 双语合作伙伴门户",
    itemsEn: [
      "Bilingual (EN/CN) partnership directory with logos and details",
      "Login and admin approval for registering partnerships",
      "Persistent database storage",
      "Cosmic navy / gold / aqua styling after the Li Fo Venture Notes site",
    ],
    itemsCn: [
      "双语（中/英）合作伙伴目录，含标识与详情",
      "登录与管理员审批的合作登记流程",
      "持久化数据库存储",
      "沿用李佛创投笔记网站的深蓝 / 金 / 湖蓝风格",
    ],
  },
];
