// System version log — shown to all signed-in users (upgrade report since v1).
export interface VersionEntry {
  version: string;
  date: string; // YYYY-MM-DD
  by: string; // author (GitHub: lklfred = Fred Li)
  titleEn: string;
  titleCn: string;
  itemsEn: string[];
  itemsCn: string[];
}

export const CURRENT_VERSION = "5.7";

export const VERSIONS: VersionEntry[] = [
  {
    version: "5.7",
    date: "2026-07-22",
    by: "Fred Li",
    titleEn: "Smoother registration, edit-rights requests & CV extract",
    titleCn: "更顺畅的注册、编辑权限申请与简历提取",
    itemsEn: [
      "Colleagues with a gobi.vc email are signed in immediately after registering, and their photo and title are pulled from the gobi.vc team page automatically",
      "Viewers can request edit rights from their profile — the request shows as a badge in the admin team table and clears once a role is set",
      "Advisor form — new AI extract from a pasted CV or biography, alongside the LinkedIn auto-sync",
      "Sync from gobi.vc now matches the name typed in the form (not only the saved one) and tolerates extra middle names",
      "R&D planner — pick the project from a list of existing projects or add a new one",
      "Partners and Network merged into one page — the star map stays as a view toggle on Partners",
      "Cover now shows a live extract of the partnership records log in the space beside the stats",
      "Advisor form now has a single Profile URL field (LinkedIn or official page) that also drives the auto-sync — no more duplicate URL fields",
      "Profile URL now sits at the top of the advisor form, and auto-sync also pulls the person's photo from the profile page",
      "Header logo now opens gobi.vc; removed the Li Fo Venture Notes footer note",
    ],
    itemsCn: [
      "使用 gobi.vc 邮箱的同事注册后立即自动登录，并自动从 gobi.vc 团队页同步照片与职位",
      "查看者可在个人资料中申请编辑权限 — 申请在管理员团队列表中以徽章显示，设置角色后自动清除",
      "顾问表单 — 新增从粘贴的简历或传记中由AI提取信息，与 LinkedIn 自动同步并列",
      "gobi.vc 同步现在按表单中输入的姓名匹配（不仅限已保存姓名），并兼容多余的中间名",
      "研发规划 — 项目可从现有项目列表中选择，或新建项目",
      "合作伙伴与网络页面合并为一 — 星图保留为合作伙伴页的视图切换",
      "封面在统计旁的空白处新增合作记录日志的实时摘要",
      "顾问表单改为单一“主页链接”字段（LinkedIn 或官方主页），并直接驱动自动同步 — 不再有重复的链接字段",
      "主页链接移至顾问表单顶部，自动同步现在还会从主页抓取人物照片",
      "页眉标志现在链接至 gobi.vc；移除页脚“李佛创投笔记”注释",
    ],
  },
  {
    version: "5.6",
    date: "2026-07-22",
    by: "Fred Li",
    titleEn: "Advisor actions on top & sector tag control panel",
    titleCn: "顾问操作按钮置顶与行业标签控制面板",
    itemsEn: [
      "Advisor detail dialog — edit, request approval, approve/reject and delete buttons moved from the bottom to the top, right under the header",
      "Admin → Sector tags upgraded into a control panel — assign a colour to each tag from a preset palette; coloured tags show across advisor and partner pages",
      "Reorder tags with up/down arrows — the order applies everywhere tags are listed and filtered",
      "Usage counts per tag — see at a glance how many advisors and partners carry each tag before editing or deleting it",
    ],
    itemsCn: [
      "顾问详情弹窗 — 编辑、发起审批、通过/退回与删除按钮从底部移至顶部，紧贴标题下方",
      "管理后台 → 行业标签升级为控制面板 — 可从预设色板为每个标签指定颜色，并在顾问与伙伴页面生效",
      "上下箭头调整标签顺序 — 顺序在所有标签列表与筛选中统一生效",
      "每个标签显示使用量 — 编辑或删除前一目了然有多少顾问与伙伴使用该标签",
    ],
  },
  {
    version: "5.5.1",
    date: "2026-07-22",
    by: "Ameen Mohd Fairuz",
    titleEn: "Functional email delivery",
    titleCn: "邮件发送功能上线",
    itemsEn: [
      "Email delivery is now functional — registration confirmations and password-reset links are sent through a configurable SMTP mail server",
      "Configurable mail settings (MAIL_SERVER, MAIL_PORT, MAIL_USE_TLS, MAIL_USERNAME, MAIL_PASSWORD, MAIL_DEFAULT_SENDER); the earlier Gmail settings still work",
      "When mail is not configured, features still degrade gracefully — registration succeeds without a confirmation email and reset falls back to secret questions",
    ],
    itemsCn: [
      "邮件发送已可用 — 注册确认与密码重置链接现通过可配置的 SMTP 邮件服务器发送",
      "可配置的邮件设置（MAIL_SERVER、MAIL_PORT、MAIL_USE_TLS、MAIL_USERNAME、MAIL_PASSWORD、MAIL_DEFAULT_SENDER）；原有 Gmail 设置仍然可用",
      "未配置邮件时功能仍优雅降级 — 注册无需确认邮件即可完成，重置回退到密保问题",
    ],
  },
  {
    version: "5.5",
    date: "2026-07-21",
    by: "Fred Li",
    titleEn: "Advisor CRM — sector tags, momentum & approval email",
    titleCn: "顾问CRM — 行业标签、互动热度与审批邮件",
    itemsEn: [
      "Sector tags shared by advisors and domain knowledge partners — filter both lists by sector; tags are managed by admins in the new Admin → Tags tab",
      "Advisor CRM — optional date of birth (DD/MM, year optional), public listing clearance flag (default no), and an internal activities log (meetings, calls, events, notes) per advisor",
      "Momentum indicator — a dot beside each advisor shows engagement freshness (active / warm / dormant) based on the latest logged activity; filter by momentum",
      "One-click approval request email — Gobi-styled email preview addressed to the COO office (configurable in Admin → Settings), cc Fred Li, opens in your mail client",
      "LinkedIn auto-sync — paste a LinkedIn URL on the advisor form and let AI fill name, background, domains and roles; includes a paste-text fallback when LinkedIn blocks fetching",
      "Advisors page now matches the partners page — grid or list view, sort options, display toggles, and sector tag & momentum filters; a team workflow diagram shows the register → fact-check → approval → clearance → public pipeline",
      "Activities, birthdays and momentum stay internal — viewers see none of them, on screen or via the API",
    ],
    itemsCn: [
      "顾问与领域知识伙伴共用行业标签 — 两个列表均可按行业筛选；标签由管理员在“管理后台 → 标签”统一管理",
      "顾问CRM — 可选生日（日/月，年份可留空）、公开展示授权标记（默认否），以及每位顾问的内部互动记录（会议、通话、活动、备注）",
      "互动热度指示 — 顾问姓名旁的圆点根据最近互动显示活跃/温热/沉寂状态，并支持按热度筛选",
      "一键生成审批邮件 — 戈壁风格邮件预览，收件人为COO办公室（可在“管理后台 → 设置”配置），抄送 Fred Li，一键在邮件客户端打开",
      "LinkedIn 自动同步 — 在顾问表单粘贴 LinkedIn 链接，AI 自动填充姓名、背景、领域与职务；LinkedIn 拦截抓取时可改为粘贴文本",
      "顾问页面与伙伴页面看齐 — 卡片/列表视图、排序、显示选项、行业标签与热度筛选；新增团队工作流程图，展示登记 → 核实 → 审批 → 授权 → 公开的流程",
      "互动记录、生日与热度仅限内部 — 浏览者在页面与接口均不可见",
    ],
  },
  {
    version: "5.0",
    date: "2026-07-21",
    by: "Fred Li",
    titleEn: "Advisor Network — people, photos & deep links",
    titleCn: "顾问网络 — 人物、照片与深度互联",
    itemsEn: [
      "New Advisor Network section — honourary advisors, domain knowledge partners and mentors, each with photo, multiple jobs & roles, expert domains, background and Gobi PICs",
      "21 advisors migrated from the team list, fact-checked against official web sources, with photos auto-pulled from university and company profile pages",
      "Organizations that advise us (Esri China (HK), OASA) now live in the partner list with a gold 'Our Domain Knowledge Partner' badge instead of a separate list",
      "Everything is inter-linked — admin console records and update-log entries open the partner page, partner pages show their advisors, and an advisor's organization jumps to the partner record",
      "Photo uploads generate an HD copy and a thumbnail automatically; advisor emails and engagement notes stay visible to staff only",
      "Deep links for sharing — /partner/:id and /advisors/:id open the record directly",
    ],
    itemsCn: [
      "新增顾问网络板块 — 荣誉顾问、领域知识伙伴与导师，包含照片、多重职务、专长领域、背景与戈壁负责人",
      "从团队名单迁移 21 位顾问，逐一对照官方网页核实，并自动从大学及公司官网抓取照片",
      "机构类顾问（Esri中国（香港）、OASA）并入合作伙伴列表，以金色“领域知识伙伴”徽章标识，不再单独维护",
      "全面互联 — 管理后台记录与更新日志可直接打开伙伴页面，伙伴页面展示关联顾问，顾问职务中的机构可跳转至伙伴记录",
      "上传照片自动生成高清版与缩略图；顾问邮箱与合作情况仅团队成员可见",
      "支持深度链接分享 — /partner/:id 与 /advisors/:id 可直接打开对应记录",
    ],
  },
  {
    version: "4.7",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Two-layer regions & interactive star map",
    titleCn: "两层地区分类与可交互星图",
    itemsEn: [
      "Regions now follow a best-practice two-layer model — broad macro-regions (Greater China, Southeast Asia, Northeast Asia, South Asia, Global) each grouping the specific territories, so Southeast Asia correctly includes Singapore, Malaysia, Indonesia, Vietnam and the Philippines",
      "Renamed the old 'International' bucket to 'Global' for anything that cannot be placed in a specific region",
      "The region filter and the star map are now mutually linked — click a region hub on the map to filter to it, and it highlights in gold; clear it and both update together",
      "Fixed a scroll bug where long people-picker lists were cut off at the bottom of the screen on smaller devices",
    ],
    itemsCn: [
      "地区采用最佳实践的两层分类 — 宏观大区（大中华区、东南亚、东北亚、南亚、全球）分别统领具体地区，东南亚现已正确包含新加坡、马来西亚、印尼、越南与菲律宾",
      "将原来的“国际”归类重命名为“全球”，用于无法归入具体地区的伙伴",
      "地区筛选与星图现已双向联动 — 在星图上点击地区节点即可筛选并以金色高亮，取消时两者同步更新",
      "修复在较小屏幕上选择负责人时长列表被屏幕底部截断、无法滚动的问题",
    ],
  },
  {
    version: "4.6",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Updates tabs & smoother rights editing",
    titleCn: "动态双日志与更顺手的权限编辑",
    itemsEn: [
      "Updates page split into two tabs — the system update log (every release, newest first) and a new partnership records log that lists every partner by date, newest first",
      "Admin rights matrix now stages your changes — tick the boxes (they highlight instantly) and save the whole row in one go, instead of a slow save on every click, with a Reset to discard unsaved edits",
      "Removed the duplicate internal-testing note in the bottom corner",
    ],
    itemsCn: [
      "动态页拆分为两个标签 — 系统更新日志（每次发布，最新在前）与全新的合作记录日志（按日期列出每家合作伙伴，最新在前）",
      "管理后台权限矩阵改为暂存式编辑 — 勾选后立即高亮，整行一次性保存，不再每次点击都缓慢保存，并可一键重置放弃未保存的更改",
      "移除右下角重复的内部测试提示",
    ],
  },
  {
    version: "4.5",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Desert scene, R&D planner, display options & rights matrix",
    titleCn: "沙漠场景、研发规划、显示选项与权限矩阵",
    itemsEn: [
      "New Developer R&D Planner — dev/admin-only roadmap of the ecosystem's modules, functions and agents on a date timeline with teammate tags, built to show management",
      "Light mode now opens onto a cinematic Gobi desert — drifting dunes, wind-blown sand and a slow camel caravan with long shadows; dark mode keeps the galaxy",
      "Display options on cards and the star map — toggle NEW, LP star, PIC, region, stage and category blocks before screenshotting as a slide",
      "Admin accounts redesigned as a rights checkbox matrix (View / Edit / IR / Dev / Admin) with a plain-language legend, including the new Developer tag",
      "Admins can edit any member's name, title and photo, and run the gobi.vc sync for them",
      "Roles and network synced from fred-li.vercel.app — updated title and nine new ecosystem partners across HK universities, NUS BLOCK71, BIOCHINA, Tencent Education, RITS, GBA NTIC and LEAP East",
      "Related sites in the footer (gobi.vc and fred-li.vercel.app), and the update log now shows the author of each release",
    ],
    itemsCn: [
      "新增开发者研发规划 — 仅开发者与管理员可见，以时间线展示生态内模块、功能与智能体的建设计划，带团队成员标签，可直接向管理层展示",
      "浅色模式呈现电影感戈壁沙漠 — 沙丘漂移、风沙拂过、驼队缓行并投下长影；深色模式保留星空",
      "卡片与星图新增显示选项 — 截图做幻灯片前可自由隐藏 NEW、LP 星标、负责人、地区、阶段与类别信息块",
      "管理后台账号改为权限勾选矩阵（查看 / 编辑 / IR / 开发 / 管理），含新增的开发者标签，并附通俗易懂的权限说明",
      "管理员可编辑任何成员的姓名、职位与照片，并可代为执行 gobi.vc 同步",
      "角色与网络与 fred-li.vercel.app 同步 — 更新职位，并新增九家生态伙伴（香港高校、NUS BLOCK71、BIOCHINA、腾讯教育、深圳清华研究院、大湾区国创中心、LEAP East）",
      "页脚新增相关网站（gobi.vc 与 fred-li.vercel.app），系统更新日志显示每次发布的作者",
    ],
  },
  {
    version: "4.4",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Galaxy interface",
    titleCn: "星系界面",
    itemsEn: [
      "Animated starry-galaxy background across the portal, including the sign-in screen — twinkling stars, drifting nebulas and the occasional shooting star",
      "Glass interface — cards, dialogs and panels are now slightly translucent with a soft blur so the galaxy shows through",
      "Adapts to light and dark mode, and respects reduced-motion system settings",
    ],
    itemsCn: [
      "全站动态星空背景（含登录页）— 星光闪烁、星云漂移，偶有流星划过",
      "玻璃质感界面 — 卡片、弹窗与面板微透明并带柔和模糊，星空若隐若现",
      "自适应深浅色模式，并遵循系统的减少动效设置",
    ],
  },
  {
    version: "4.3",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "LP status, smarter AI intake & data upgrade",
    titleCn: "LP 状态、更智能的 AI 录入与数据升级",
    itemsEn: [
      "Remember me — stay signed in on this device between visits",
      "One-click profile sync from gobi.vc (photo and title) after registering",
      "Smarter AI intake — detects documents, links or plain text, fetches linked pages, summarises the relationship and suggests the PIC automatically",
      "LP status per partner (N/A / Target LP / LP) — visible only to the IR team, with a new IR-team toggle in admin accounts",
      "Full partnership info upgrade — researched descriptions, PICs, start dates and LP flags across the directory, sourced from gobi.vc and public news",
      "New Advisors section (coming soon) and a portal-wide disclaimer in the footer",
    ],
    itemsCn: [
      "记住我 — 在本设备上保持登录状态",
      "注册后可一键从 gobi.vc 同步个人资料（照片与职位）",
      "更智能的 AI 录入 — 自动识别文档、链接或纯文本，拓展链接内容，总结合作关系并自动建议负责人",
      "合作伙伴 LP 状态（无 / 目标 LP / LP）— 仅 IR 团队可见，管理后台新增 IR 团队开关",
      "合作信息全面升级 — 基于 gobi.vc 与公开报道补充描述、负责人、起始日期与 LP 标识",
      "新增顾问板块（即将上线），并在页脚添加免责声明",
    ],
  },
  {
    version: "4.2",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Filters, feedback & photo galleries",
    titleCn: "筛选、反馈与照片展示",
    itemsEn: [
      "Filters now support selecting multiple options at once (category, stage, region, year)",
      "New Updates page — full system update log plus system requests & feedback",
      "Submit a system request from the portal and track its status (open / in progress / solved / declined)",
      "Admins can reply to requests, manage them in a new admin tab, and add team accounts directly",
      "Search boxes added to the admin console (partnership records and team accounts)",
      "Partner photo carousels — example galleries added for HKU, HKUST and HKIC",
    ],
    itemsCn: [
      "筛选器支持多选（类别、阶段、地区、年份）",
      "新增系统动态页面 — 完整更新日志与系统需求反馈",
      "可在门户内提交系统需求并跟踪处理状态（待处理 / 处理中 / 已解决 / 已拒绝）",
      "管理员可回复需求、在新的管理页签中处理，并可直接新增团队账户",
      "管理后台新增搜索框（合作记录与团队账户）",
      "合作伙伴照片轮播 — 已为港大、科大与港投公司添加示例图库",
    ],
  },
  {
    version: "4.1",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Account security & email",
    titleCn: "账户安全与邮件",
    itemsEn: [
      "Forgot password — reset via an emailed link or by answering secret questions",
      "Secret questions are set during registration (bilingual, answers stored hashed)",
      "Confirmation email sent when registration completes",
      "@gobi.vc registrations are approved automatically as viewers — sign in right away",
    ],
    itemsCn: [
      "忘记密码 — 可通过邮箱重置链接或回答密保问题重置",
      "注册时设置密保问题（中英双语，答案加密存储）",
      "注册完成后自动发送确认邮件",
      "@gobi.vc 邮箱注册自动获批为查看者，无需等待审批",
    ],
  },
  {
    version: "4.0",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Login-first, Gobi rebrand, timeline & audit",
    titleCn: "登录优先、Gobi 品牌升级、时间线与审计",
    itemsEn: [
      "Sign-in is now required before viewing any content",
      "Rebranded to Gobi Partners with the official logo (light/dark)",
      "Partnership stage (01-05) and collaboration level merged — stage is the single source of truth",
      "New timeline view with date-range and year filters",
      "Hall of Fame is now a mode inside the star map, with full filters",
      "Export records to Excel or CSV with selectable fields",
      "Start date is compulsory; AI quick-fill estimates it from documents",
      "AI quick-fill now runs on DeepSeek (PDF / DOCX / text)",
      "NEW badge on entries added within the last month",
      "Lists sorted by strategic level, then alphabetically",
      "Per-partner change log (who changed what, when) for audit",
      "Editable user profiles — title and photo",
      "Edit button in partner details for signed-in staff and admins",
      "Admin table shows PIC and start date columns",
    ],
    itemsCn: [
      "查看任何内容前必须先登录",
      "品牌升级为 Gobi Partners，启用官方标识（明暗两版）",
      "合作阶段（01-05）与协作等级合并 — 以阶段为唯一标准",
      "新增时间线视图，支持日期区间与年份筛选",
      "荣誉殿堂并入星图模式，支持全部筛选条件",
      "支持导出 Excel 或 CSV，可自选字段",
      "开始日期为必填项；AI 速填可从文档中估算",
      "AI 速填改用 DeepSeek（支持 PDF / DOCX / 文本）",
      "近一个月新增条目显示 NEW 标识",
      "列表按战略等级排序，再按字母排序",
      "每个伙伴均有变更记录（谁、何时、改了什么）以供审计",
      "用户可编辑个人资料 — 职位与照片",
      "登录后可在伙伴详情中直接编辑",
      "管理表新增负责人与开始日期列",
    ],
  },
  {
    version: "3.0",
    date: "2026-07-12",
    by: "Fred Li",
    titleEn: "Full partner sync, star map & multi-PIC",
    titleCn: "全量伙伴同步、星图与多负责人",
    itemsEn: [
      "Synchronised the full 55-partner database",
      "Interactive star map (network view) of the partnership ecosystem",
      "Multiple Gobi PICs per partnership with avatar groups",
      "Developer note and internal-testing banner",
    ],
    itemsCn: [
      "同步全部 55 家合作伙伴数据库",
      "合作生态互动星图（网络视图）",
      "每个合作可指定多位戈壁负责人，头像组展示",
      "开发者署名与内部测试横幅",
    ],
  },
  {
    version: "2.0",
    date: "2026-07-10",
    by: "Fred Li",
    titleEn: "Roles, AI quick-fill & attachments",
    titleCn: "角色权限、AI 速填与附件",
    itemsEn: [
      "Admin / staff / viewer roles with approval workflow",
      "AI quick-fill: paste text or upload documents to fill the form",
      "File attachments on partnership records",
      "01-05 partnership stage pipeline",
    ],
    itemsCn: [
      "管理员 / 员工 / 访客角色与审批流程",
      "AI 速填：粘贴文本或上传文档自动填表",
      "合作记录支持文件附件",
      "01-05 合作阶段管道",
    ],
  },
  {
    version: "1.0",
    date: "2026-07-08",
    by: "Fred Li",
    titleEn: "First release — bilingual partnership portal",
    titleCn: "首个版本 — 双语合作伙伴门户",
    itemsEn: [
      "Bilingual (EN/CN) partnership directory with logos and details",
      "Login and admin approval for registering partnerships",
      "Persistent database storage",
      "Cosmic navy / gold / aqua styling after the Li Fo Venture Notes site",
    ],
    itemsCn: [
      "双语（中/英）合作伙伴目录，含标识与详情",
      "登录与管理员审批的合作登记流程",
      "持久化数据库存储",
      "沿用李佛创投笔记网站的深蓝 / 金 / 湖蓝风格",
    ],
  },
];
