// System version log — shown to all signed-in users (upgrade report since v1).
export interface VersionEntry {
  version: string;
  date: string; // YYYY-MM-DD
  by: string; // author (GitHub: lklfred = Fred Li)
  titleEn: string;
  titleCn: string;
  itemsEn: string[];
  itemsCn: string[];
}

export const CURRENT_VERSION = "6.04";

export const VERSIONS: VersionEntry[] = [
  {
    version: "6.04",
    date: "2026-07-28",
    by: "Fred Li",
    titleEn: "v6.04 — advisor change log, CV filing with AI extraction, signed letter filing, tidier contact card",
    titleCn: "v6.04 — 顾问变更日志、简历存档与AI提取、签署函件存档、更整洁的联系卡片",
    itemsEn: [
      "Advisor change log: every create, edit, approval, rejection, deletion and workflow step on an advisor record is now logged with who did it and when — shown at the bottom of the advisor detail view for staff; only field names are recorded, never sensitive values",
      "CV filing: the From CV / bio dialog now accepts a PDF, Word or TXT file upload — the file is stored on the advisor record for later download, and AI reads it to fill the form",
      "Standardised experience format: AI-extracted backgrounds now come as a clean chronology — one line per position, most recent first, in the shape Year–Year — Organization — Role & scope, followed by education",
      "Signed letter filing: the onboarding workflow's Signed back step now takes the actual signed letter file — uploading it files the document for record and completes the step automatically",
      "Contact & links tidied: emails, mobile, WeChat, profile links, filed CVs, origin staff, current PIC and birthday are now grouped in one orderly card instead of scattered rows",
      "Engineering: a written SOP now requires every GitHub update to be recorded in the repository update log (docs/UPDATE_LOG.md) — check first, work, log back",
    ],
    itemsCn: [
      "顾问变更日志：顾问记录的每次创建、编辑、批准、拒绝、删除及流程操作现在都会记录操作人与时间——员工可在顾问详情底部查看；日志只记录字段名称，绝不记录敏感内容",
      "简历存档：「从简历/传记提取」对话框现在支持上传 PDF、Word 或 TXT 文件——文件存档在顾问记录中可随时下载，并由 AI 读取内容自动填表",
      "经历格式标准化：AI 提取的背景信息现在以清晰的时间线呈现——每段职务一行、由近及远，格式为 年份–年份 — 机构 — 职务与职责，学历同格式列于其后",
      "签署函件存档：入职流程的「已签回」步骤现在可直接上传签署好的函件文件——上传即存档备查，并自动完成该步骤",
      "联系方式整理：邮箱、手机、微信、主页链接、已存档简历、来源同事、当前负责人与生日现在归入一张整齐的卡片，不再散落各处",
      "工程规范：新增书面 SOP，要求每次 GitHub 更新必须记入仓库更新日志（docs/UPDATE_LOG.md）——先查后做、做完回记",
    ],
  },
  {
    version: "6.03",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "v6.03 — a clearer 4-level partnership pipeline, refreshed data",
    titleCn: "v6.03 — 更清晰的四级合作管线，数据焕新",
    itemsEn: [
      "Partnership levels simplified from 5 to 4 with crisp definitions: 01 New / Target (on our radar, no relationship yet), 02 Engaged (first meeting, activity or contact done), 03 Progress Partnership (advanced meetings, collaborations done, track record), 04 Strategic Partnership (MoU signed, strategic framework or deeper)",
      "Every level badge now explains its meaning on hover, and the register / edit forms show a compact level guide with the selected level highlighted, so records are classified consistently at the point of entry",
      "All existing records migrated automatically: MOU & Agreement and Strategic merge into 04 Strategic Partnership; Progressive becomes 03 Progress Partnership",
      "Registry refreshed from public sources: new partner records for organizations Gobi already works with, and updated team photos for key partners from recent press coverage",
    ],
    itemsCn: [
      "合作层级由五级精简为四级，定义更清晰：01 新目标（已列入视野、尚未建立联系）、02 接洽中（已完成首次会面、活动或联系）、03 深化合作（深入会谈、已开展合作、积累往绩）、04 战略伙伴（已签署备忘录、建立战略框架或更深层合作）",
      "所有层级徽章悬停即显说明，登记与编辑界面新增紧凑的级别说明并高亮当前所选级别，录入时即可统一口径",
      "存量记录已自动迁移：原「MOU 与协议」及「战略」并入 04 战略伙伴，原「深化合作」调整为 03 深化合作",
      "登记册依据公开来源焕新：补录 Gobi 已有合作但未入册的机构，并从近期新闻报道更新重点伙伴的团队照片",
    ],
  },
  {
    version: "6.02",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "v6.02 — reliable map reset, the sun and moon say hi back",
    titleCn: "v6.02 — 星图复位更可靠，太阳和月亮也会回应你",
    itemsEn: [
      "Star maps: clicking the central Gobi hub now reliably resets the view — previously even a one-pixel hand tremor during the click made the map treat it as a drag and ignore it; all node clicks (partners, advisors, regions) are steadier for the same reason",
      "Background play: the sun (by day) and the moon (by night) now react when clicked — a friendly double wink of their glow and a little heart that floats up and fades away",
    ],
    itemsCn: [
      "星图：点击中央 Gobi 枢纽现在能够可靠地复位视图 — 此前点击时哪怕手抖动一个像素，地图也会误判为拖拽而忽略点击；同理，所有节点（合作伙伴、顾问、地区）的点击都更稳定了",
      "背景互动：白天的太阳与夜晚的月亮现在也会回应点击 — 光晕友好地眨两下眼，并有一颗小爱心缓缓升起、淡出",
    ],
  },
  {
    version: "6.01",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "v6.01 — photo uploads, edit safety, your request tracker, livelier world",
    titleCn: "v6.01 — 照片上传、编辑保护、请求追踪、更生动的世界",
    itemsEn: [
      "Photos for partner activities: upload image files directly (drag-and-drop or file picker) instead of pasting URLs — photos are stored on our server, grouped by network, auto-thumbnailed for fast carousels, and an HD download is one click away",
      "Star maps: hover info now appears instantly, and clicking the central Gobi hub zooms the map back out to the full view",
      "Advisor cards and list rows now show the person in charge (PIC), matching the partnership views",
      "Your profile now includes a mandatory email address, ready for future sync and automated workflows",
      "Edit safety: closing any editor with unsaved changes now asks whether to save, discard or keep editing — partnership editor, advisor editor, your profile, and admin settings/templates are all covered",
      "Updates page: a personal tracker shows the status of your own requests at a glance — status chips with counts, a Mine/All view for the team, and an updated date on each reply",
      "Sign-in warp: the zoom-in now fades through a translucent gradient veil into the portal instead of a hard dark cut",
      "Small thank-you notes slide in (and fade out on their own) after you submit records, feedback or edits",
      "The desert is gently interactive: click near a camel, traveller, palm or star and it says hi — a little hop, a rustle or a twinkle — kept deliberately light so nothing slows down",
      "Speed: the app now loads in slices — the sign-in screen arrives first and each page fetches its own code on demand, so the first paint is much lighter; the animated backdrop also waits for an idle moment before it starts",
    ],
    itemsCn: [
      "合作伙伴活动照片：支持直接上传图片文件（拖放或选择文件），不再需要粘贴链接 — 照片存储在我们的服务器上，按网络分组，自动生成缩略图令轮播更快，并可一键下载高清原图",
      "星图：悬停信息即时显示；点击中央 Gobi 枢纽即可缩小回全景视图",
      "顾问卡片与列表行现在同样显示负责人（PIC），与合作伙伴视图一致",
      "个人资料新增必填邮箱字段，为后续同步与自动化流程做准备",
      "编辑保护：在任何编辑器中有未保存修改时关闭，会询问保存、放弃还是继续编辑 — 覆盖合作伙伴编辑器、顾问编辑器、个人资料以及管理设置/模板",
      "更新页：新增个人请求追踪器，一眼看到自己每条请求的处理状态 — 状态标签带数量、团队可切换「我的/全部」视图、每条回复标注更新日期",
      "登录穿越动画改为半透明渐变光幕，柔和地淡入门户，不再是生硬的暗场切换",
      "提交记录、反馈或编辑后，右侧会滑出小小的感谢提示，并自动淡出，无需点击",
      "沙漠世界变得轻盈可互动：点击骆驼、行者、棕榈或星星附近，它会向你打个招呼 — 轻轻一跳、一阵摇曳或一次闪烁 — 刻意保持简洁，不影响速度",
      "速度：应用改为分片加载 — 登录页最先到达，每个页面按需加载自己的代码，首屏轻量许多；动态背景也会等浏览器空闲后再启动",
    ],
  },
  {
    version: "6.0",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "v6.0 — faster loads, desert-caravan theme, advisor star maps",
    titleCn: "v6.0 — 加载提速、沙漠驼队主题、顾问星图",
    itemsEn: [
      "Speed: advisor and partner lists now load from a server-side cache with browser revalidation (304), the roster list ships without heavy photos (thumbnails only), and both lists are prefetched right after login — warm navigation feels instant",
      "Staff picker (PIC): a pinned search bar filters colleagues by name, title or office; selected people show as removable chips; the list scrolls smoothly",
      "R&D and Admin entries carry a Restricted badge that explains their special access rights",
      "System requests now live at the top of the R&D page as a compact triage log (open first, then resolved); admins update status and reply inline",
      "Letter templates moved into Admin → Settings as a collapsible section",
      "Visual: light and dark mode now share one desert world — dunes, an oasis with palms, and a caravan of camels and walkers moving forward as a team; day has sun, drifting sand and butterflies, night has the starry galaxy, meteors, a crescent moon and fireflies",
      "After login, a brief interstellar warp zooms you into the system",
      "Partner network: advisors appear as small gold stars orbiting their linked organization, with a toggle and tooltips (name · role @ org); click one to open the profile",
      "Advisor page: a new Star map view shows the advisory constellation — org hubs with linked advisors clustered around them, unlinked advisors on the outer ring; all filters apply",
    ],
    itemsCn: [
      "速度：顾问与合作伙伴列表改用服务器端缓存并支持浏览器再验证（304），名册列表不再携带大图（仅缩略图），登录后立即预取两份列表——再次切换页面几乎即时",
      "同事选择器（PIC）：置顶搜索栏可按姓名、职务或办公室过滤；已选人员以可移除的标签展示；列表滚动顺滑",
      "研发与管理入口新增「内部」徽章，说明其特殊访问权限",
      "系统需求改为在研发页顶部以紧凑日志形式分流（先未决后已结）；管理员可在行内更新状态并回复",
      "函件模板移入管理 → 设置，作为可折叠区块",
      "视觉：明暗两种模式共享同一片沙漠——沙丘、绿洲棕榈，以及骆驼与行者组成的驼队团队一路前行；白天有太阳、流沙与蝴蝶，夜晚有星河、流星、新月与萤火虫",
      "登录后新增短暂的星际穿越动画，带你进入系统",
      "合作网络：顾问以小金星形式围绕其关联机构运行，可开关显示，悬停显示提示（姓名·角色@机构），点击打开详情",
      "顾问页：新增「星图」视图展示顾问星座——机构枢纽周围聚集关联顾问，未关联顾问位于外环；所有筛选同样生效",
    ],
  },
  {
    version: "5.15",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Advisor–partner organization linking",
    titleCn: "顾问与合作伙伴机构关联",
    itemsEn: [
      "Advisor roles: the organization field and the partner link are now one searchable dropdown — type to search partners (EN or CN), pick to link, or keep free text; unknown organizations can be created as a new partner record in one click",
      "Organizations typed by hand or harvested by auto-sync are automatically matched to the partner registry (exact name, alias, acronym such as HKUST, word-order-free acronym such as HKU, Chinese name) — only an unambiguous match links, e.g. Prof. Nancy MAN's HKU and Andy WONG's HKUST roles now link to those partners",
      "One-off backfill re-ran the matcher over all existing advisors, so previously unlinked roles now appear on the partner's page",
      "Sub-entities show their parent in the dropdown (HKU Medicine · The University of Hong Kong); linked organizations show a building mark on the role row",
      "Auto-sync now explains itself when a profile page cannot be read (site offline or blocking automated access) before offering the paste-text fallback",
    ],
    itemsCn: [
      "顾问角色：机构字段与合作伙伴关联合并为一个可搜索下拉框 — 输入即可搜索（中英文均可），选中即关联，也可保留自由文本；未收录的机构可一键创建为新合作伙伴",
      "手动输入或自动同步获取的机构会自动与合作伙伴库匹配（全名、别名、缩写如 HKUST、乱序缩写如 HKU、中文名）— 仅在匹配唯一时才会关联，例如 Nancy MAN 教授的 HKU 与 Andy WONG 的 HKUST 角色现已关联到对应合作伙伴",
      "已对全部现有顾问执行一次性回填匹配，此前未关联的角色现会出现在合作伙伴页面",
      "子机构在下拉框中显示所属母体（香港大学医学院 · 香港大学）；已关联的机构在角色行上显示建筑标记",
      "当无法读取资料页面时（网站失效或屏蔽自动访问），自动同步会先给出提示说明，再提供粘贴文本的备选方式",
    ],
  },
  {
    version: "5.14",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Photo identity gate — fix wrong-person photo on auto-sync",
    titleCn: "照片身份门控 — 修复自动同步拉错照片",
    itemsEn: [
      "Fixed: on team pages listing several people, advisor auto-sync could apply a colleague's photo (a surname match such as Michael WONG vs Andy WONG was wrongly treated as the same person) — photo matching now requires the person's given name or Chinese name",
      "Every candidate photo is cross-checked against the record's identity factors (name, Chinese name, LinkedIn, email) using its alt text, the caption next to it, and its file name — the AI's pick is verified by the same rule and the strongest match wins",
      "If no photo on the page can be tied to the person, the photo is left untouched — a missing photo beats a wrong one",
      "Auto-sync and From CV / bio moved to the top-right corner of the advisor dialog — they are record-level actions that harvest all links (profile URL + LinkedIn) and identity factors together, not helpers of a single field",
    ],
    itemsCn: [
      "修复：在列出多人的团队页面上，顾问自动同步可能套用同事的照片（仅姓氏相同如 Michael WONG 与 Andy WONG 被误判为同一人）—— 照片匹配现在必须命中名字或中文姓名",
      "每张候选照片都会与记录的身份因子（姓名、中文名、LinkedIn、邮箱）交叉核对 — 依据 alt 文本、照片旁的说明文字及文件名；AI 的选择也经同一规则验证，匹配度最强者胜出",
      "若页面上没有照片能与本人关联，则不更改照片 — 宁缺勿错",
      "自动同步与简历提取按钮移至顾问对话框右上角 — 它们是记录级操作，会同时汇集所有链接（资料链接 + LinkedIn）与身份因子，而非单一字段的辅助功能",
    ],
  },
  {
    version: "5.13",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Multi-factor auto-sync for advisors and partners",
    titleCn: "顾问与合作方的多因子自动同步",
    itemsEn: [
      "Advisor auto-sync now harvests every link on the record — the profile URL and the LinkedIn URL are fetched together, readable pages are merged into one material set, photo candidates are pooled across pages, and the AI produces a single best-of answer",
      "Advisor auto-sync works from any factor — a profile URL, a LinkedIn URL, or pasted text alone is enough; whatever combination exists is used and the identity lock (name, LinkedIn, email) still applies",
      "Partner records now have their own auto-sync — an Auto-sync button next to the website field in the edit dialog fetches the organisation's website and enriches the profile fields (Chinese name, category, region, descriptions, contacts, type, background)",
      "Partner auto-sync is anchored to the organisation — the form's name and website are the extraction criteria, and if the material turns out to be about a different organisation the sync stops and changes nothing",
      "Partner sync never touches relationship fields — stage, start date and PICs stay as your team recorded them; only public-profile fields are enriched",
      "Register page AI quick-fill upgraded — it accepts a website alone (no pasted text needed), fetches the form's website as an extra source, and anchors extraction to the organisation once the form names one",
    ],
    itemsCn: [
      "顾问自动同步现会汇集记录中的所有链接 — 资料链接与 LinkedIn 链接同时抓取，可读页面合并为同一材料集，照片候选跨页面汇总，AI 输出单一最优结果",
      "顾问自动同步支持任意因子 — 仅有资料链接、LinkedIn 链接或粘贴文本均可运行；系统使用现有的任意组合，身份锁定（姓名、LinkedIn、邮箱）仍然生效",
      "合作方记录新增自动同步 — 编辑对话框官网字段旁的自动同步按钮会抓取机构官网并补充资料字段（中文名、类别、地区、简介、联系人、类型、背景）",
      "合作方自动同步锁定机构 — 以表单中的名称与官网作为提取条件；若材料属于另一个机构，同步会停止且不作任何修改",
      "合作方同步不触碰合作关系字段 — 阶段、开始日期与负责人保持团队记录不变，仅补充公开资料字段",
      "登记页 AI 快速填充升级 — 仅填官网即可运行（无需粘贴文本），表单官网作为额外来源抓取，表单已命名机构时提取会锁定该机构",
    ],
  },
  {
    version: "5.12",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Password self-service, smarter auto-sync, and faster advisor profiles",
    titleCn: "密码自助管理、更智能的自动同步与更快的顾问资料加载",
    itemsEn: [
      "Auto-sync is now locked to the advisor being edited — the name in the form (plus the LinkedIn address and email) is used as the extraction criteria, and if the linked page turns out to be about a different person the sync stops and changes nothing",
      "Auto-sync photo selection rebuilt — the AI now picks the person's portrait from the page's images and company logos, icons and banners are excluded; when no clear portrait exists the photo is left blank instead of guessing",
      "Auto-sync now standardises what it fills in — names as 'Given SURNAME' with honorifics, Chinese names in characters only, factual 2-4 sentence bios, 2-5 Title-Case expertise domains, organisation names without legal suffixes, and exactly one primary role",
      "New Security section in your profile — change your password with your current one, or request a reset link by email (email delivery arrives with the Gmail integration)",
      "Admins can force-reset any team account from Team accounts — a one-time temporary password is generated and the owner must set a new password at next sign-in",
      "Advisor profiles now open instantly — the card renders from already-loaded data while the HD photo loads in the background, and the server fetches profile data in parallel",
      "Header cleanup — the duplicated subtitle line is gone and clicking the logo returns to the portal home page",
      "The scoreboard moved into the admin portal as a tab — it no longer appears in the top navigation and stays hidden from non-admin accounts",
    ],
    itemsCn: [
      "自动同步现已锁定正在编辑的顾问 — 以表单中的姓名（及 LinkedIn 地址、邮箱）作为提取条件；若链接页面属于另一个人，同步会停止且不作任何修改",
      "自动同步照片选择重建 — AI 从页面图片中识别人物肖像，自动排除公司标志、图标与横幅；无法确认肖像时留空而不会错取",
      "自动同步填充内容标准化 — 英文名按“名 + 姓（大写）”含尊称，中文名仅汉字，简历为 2-4 句客观描述，专长领域 2-5 项规范大写，机构名称去除公司后缀，且仅一个主要职位",
      "个人资料新增安全区块 — 可用当前密码修改密码，或申请邮件重置链接（邮件发送将随 Gmail 集成上线）",
      "管理员可在团队账号页强制重置任何账号密码 — 系统生成一次性临时密码，用户下次登录时必须设置新密码",
      "顾问资料卡片现在即时打开 — 先用已加载数据渲染，高清照片后台加载，服务器并行获取资料数据",
      "页眉优化 — 移除重复的副标题，点击标志返回门户首页",
      "积分榜移入管理后台标签页 — 不再显示在顶部导航，对非管理员账号保持隐藏",
    ],
  },
  {
    version: "5.11",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Editable email and letter templates in the admin portal",
    titleCn: "管理后台可编辑邮件与邀请函模板",
    itemsEn: [
      "New Templates tab in the admin portal for editing the two outreach email templates — onboarding invitation and general update — subject and body, with per-advisor placeholders such as {{name}}, {{first_name}} and {{organization}}",
      "The invitation letter body and the page-two Acknowledgment Receipt are now editable in the same tab; blank lines separate paragraphs and placeholders such as {{name}} and {{domains}} are filled per advisor in both the Word and print versions",
      "Each template section has a reset-to-default action that restores the firm's standard wording",
      "Saved template changes apply immediately to the outreach composer and to newly generated letters — no redeploy needed",
      "Direct system sending remains labelled coming soon and will be enabled once the Gmail integration is ready — copy text and mail-client options are the interim path",
    ],
    itemsCn: [
      "管理后台新增模板页，可编辑两封拓展邮件模板（入网邀请与常规更新）的主题与正文，支持 {{name}}、{{first_name}}、{{organization}} 等按顾问填充的占位符",
      "邀请函正文与第二页签收回执现在同页可编辑 — 空行分段，{{name}}、{{domains}} 等占位符在 Word 版与打印版中均按顾问自动填充",
      "每个模板区块均设恢复默认按钮，一键还原公司标准文本",
      "模板保存后立即生效于联络编辑器与新生成的邀请函，无需重新部署",
      "系统直接发送仍标注为即将推出，将在 Gmail 集成完成后启用 — 过渡期请使用复制文本或邮件客户端",
    ],
  },
  {
    version: "5.10",
    date: "2026-07-26",
    by: "Fred Li",
    titleEn: "Official invitation letter in Word and print formats, copyable emails, and AI auto-sync fixes",
    titleCn: "正式邀请函 Word 与打印版、邮件一键复制与 AI 自动同步修复",
    itemsEn: [
      "The invitation letter now follows the firm's official template — Gobi letterhead, Strictly Private & Confidential, the standard five paragraphs with the advisor's expertise filled in, and a second-page Acknowledgment Receipt for countersigning",
      "Admins can download the letter as an editable Word document or open the print view to save it as a PDF; both record the letter-issued stage automatically",
      "The onboarding cover email now asks the advisor to countersign the attached Acknowledgment Receipt and return a copy",
      "Every recipient row in the outreach send step has a new copy-text button that copies the fully resolved email — addresses, subject and body — for pasting into any mail client",
      "The approval email dialog's copy button now includes the To and Cc lines and works inside embedded previews where the clipboard is restricted",
      "Fixed AI auto-sync from profile links, which failed after the DeepSeek platform retired the model name the portal was calling",
      "Fixed two-finger trackpad scrolling in the origin-staff and PIC picker lists inside dialogs",
    ],
    itemsCn: [
      "邀请函改用公司正式模板 — 戈壁信头、Strictly Private & Confidential、标准五段正文并自动填入顾问专长，第二页为待会签的确认回执",
      "管理员可下载可编辑的 Word 版邀请函，或打开打印视图另存为 PDF，两者均自动记录“已发函”进度",
      "入职邀请邮件现会提醒顾问会签随函的确认回执并寄回副本",
      "联络工具发送步骤的每位收件人新增复制文本按钮，一键复制已解析的收件人、主题与正文，可粘贴到任意邮件客户端",
      "审批邮件弹窗的复制按钮现包含收件人与抄送行，并在剪贴板受限的内嵌预览中也能正常工作",
      "修复了从主页链接 AI 自动同步失败的问题 — 原因是 DeepSeek 平台停用了旧模型名称",
      "修复了弹窗内引荐人与对接人选择列表无法双指触控滚动的问题",
    ],
  },
  {
    version: "5.9",
    date: "2026-07-25",
    by: "Fred Li",
    titleEn: "Admin scoreboard with ledger, advisor CRM fields, grouping and a branded outreach editor",
    titleCn: "管理员专属积分榜与明细、顾问 CRM 字段、分组视图与品牌化联络编辑器",
    itemsEn: [
      "The scoreboard is now open to admin accounts only and is hidden from the menu for everyone else",
      "Scoreboard rows are anchored to team accounts, so name variants roll up to one person and colleagues who have left keep their credit under a former-staff label",
      "New scoreboard columns separate advisors originated from advisors managed, with proposed, onboarded and terminated shown underneath",
      "Scoreboard filters add a show-former-staff toggle and a role filter, and the whole table can be exported to CSV for the selected period",
      "Selecting a scoreboard row opens a ledger listing every advisor and partner credited to that person, with an originated or managing marker on each advisor",
      "The advisor form is reordered into six labelled sections — source, contact, identity, roles, classification and internal — so the profile link and auto-sync come first",
      "Advisors now carry a mobile number with a country-code picker and a WeChat ID, both staff-visible only and shown in the contact block of the detail page",
      "New origin staff field records who sourced an advisor as a permanent entry, kept after the colleague leaves, alongside the current PIC",
      "New group-by selector on the advisors page groups cards and rows by pillar, sector tag, lifecycle status, track or cohort in collapsible sections",
      "The lifecycle pill moved to the top-right corner of each advisor card in an outlined dot style so it is no longer mistaken for a sector tag",
      "The outreach tool is now a three-step editor — edit one template with placeholders, preview the resolved message per recipient, then send — with Gobi Calibri email styling",
    ],
    itemsCn: [
      "积分榜现仅向管理员账号开放，其余账号菜单中不再显示",
      "积分榜以团队账号为基准，姓名写法差异自动归并到同一人，已离职同事的贡献以“已离职·未匹配”标签保留",
      "积分榜新增列将引荐顾问与在管顾问分开统计，下方附带提名中、已加入与已终止的拆分",
      "积分榜筛选新增“显示离职员工”开关与角色筛选，并可按所选期间将整张表导出为 CSV",
      "点选积分榜中的任一行可打开明细，列出计入该同事的全部顾问与合作方，每位顾问标注引荐或在管",
      "顾问表单重排为六个分区 — 来源、联系方式、身份、职务、分类与内部 — 主页链接与自动同步置于最前",
      "顾问新增带国家/地区代码选择的手机号与微信号，仅同事可见，并在详情页联系区块中显示",
      "新增“引荐人”字段永久记录顾问的引荐来源，人员离职后仍保留，与现任对接人并列",
      "顾问页新增分组选择器，可按重点领域、行业标签、生命周期状态、背景类型或批次将卡片与列表分组，分区可折叠",
      "生命周期标签移至顾问卡片右上角，改为带状态圆点的描边样式，不再与行业标签混淆",
      "联络工具改为三步编辑器 — 编辑单一模板并使用占位符、按收件人预览实际内容、再行发送 — 邮件采用戈壁 Calibri 品牌样式",
    ],
  },
  {
    version: "5.8",
    date: "2026-07-25",
    by: "Fred Li",
    titleEn: "Advisor lifecycle, onboarding tracker, invitation letters, outreach & scoreboard",
    titleCn: "顾问生命周期、入职进度跟踪、邀请函、批量联络与业绩看板",
    itemsEn: [
      "Every advisor now carries a lifecycle status — proposed, onboarded or terminated — shown as a pill on the cards, the list and the detail page, with a matching filter on the advisors page",
      "Admins can move an advisor between lifecycle statuses from the detail page, with a confirmation step before terminating",
      "New onboarding tracker on the advisor detail page follows four stages: approval emailed, approved, letter issued and signed back, each with its own date",
      "Sending the approval email now records the approval-emailed stage automatically, and the email body includes the background and suggested engagement",
      "Admins can generate a formatted invitation letter for an advisor, which opens in a new tab ready to print or save as PDF and records the letter-issued stage",
      "New outreach tool on the advisors page composes onboarding or update emails for a batch of advisors, with editable drafts, the local mail client, or server sending",
      "Staff can export advisors and partners to CSV from the advisors page and from a new Exports tab in the admin console",
      "New scoreboard page shows partners and advisors per person in charge, with a date range filter — staff see their own row, admins see everyone",
    ],
    itemsCn: [
      "每位顾问新增生命周期状态 — 建议中、已入职或已终止 — 在卡片、列表与详情页以标签显示，顾问页可按此筛选",
      "管理员可在详情页调整顾问的生命周期状态，终止前需确认",
      "顾问详情页新增入职进度跟踪，包含四个阶段：已发送审批邮件、已批准、已出邀请函、已签回，各自记录日期",
      "发送审批邮件时自动记录“已发送审批邮件”阶段，邮件正文新增背景简介与建议合作方式",
      "管理员可生成格式化的顾问邀请函，在新标签页打开可直接打印或存为PDF，并自动记录“已出邀请函”阶段",
      "顾问页新增批量联络工具，可为多位顾问生成入职或进展邮件草稿，支持编辑、用本地邮件客户端发送或由服务器发送",
      "同事可在顾问页及管理后台新增的导出标签页中，将顾问与合作伙伴导出为CSV",
      "新增业绩看板页面，按负责人统计合作伙伴与顾问数量，可按日期区间筛选 — 同事查看本人数据，管理员查看全部",
    ],
  },
  {
    version: "5.7",
    date: "2026-07-22",
    by: "Fred Li",
    titleEn: "Smoother registration, edit-rights requests & CV extract",
    titleCn: "更顺畅的注册、编辑权限申请与简历提取",
    itemsEn: [
      "Colleagues with a gobi.vc email are signed in immediately after registering, and their photo and title are pulled from the gobi.vc team page automatically",
      "Viewers can request edit rights from their profile — the request shows as a badge in the admin team table and clears once a role is set",
      "Advisor form — new AI extract from a pasted CV or biography, alongside the LinkedIn auto-sync",
      "Sync from gobi.vc now matches the name typed in the form (not only the saved one) and tolerates extra middle names",
      "R&D planner — pick the project from a list of existing projects or add a new one",
      "Partners and Network merged into one page — the star map stays as a view toggle on Partners",
      "Cover now shows a live extract of the partnership records log in the space beside the stats",
      "Advisor form now has a single Profile URL field (LinkedIn or official page) that also drives the auto-sync — no more duplicate URL fields",
      "Profile URL now sits at the top of the advisor form, and auto-sync also pulls the person's photo from the profile page",
      "Header logo now opens gobi.vc; removed the Li Fo Venture Notes footer note",
    ],
    itemsCn: [
      "使用 gobi.vc 邮箱的同事注册后立即自动登录，并自动从 gobi.vc 团队页同步照片与职位",
      "查看者可在个人资料中申请编辑权限 — 申请在管理员团队列表中以徽章显示，设置角色后自动清除",
      "顾问表单 — 新增从粘贴的简历或传记中由AI提取信息，与 LinkedIn 自动同步并列",
      "gobi.vc 同步现在按表单中输入的姓名匹配（不仅限已保存姓名），并兼容多余的中间名",
      "研发规划 — 项目可从现有项目列表中选择，或新建项目",
      "合作伙伴与网络页面合并为一 — 星图保留为合作伙伴页的视图切换",
      "封面在统计旁的空白处新增合作记录日志的实时摘要",
      "顾问表单改为单一“主页链接”字段（LinkedIn 或官方主页），并直接驱动自动同步 — 不再有重复的链接字段",
      "主页链接移至顾问表单顶部，自动同步现在还会从主页抓取人物照片",
      "页眉标志现在链接至 gobi.vc；移除页脚“李佛创投笔记”注释",
    ],
  },
  {
    version: "5.6",
    date: "2026-07-22",
    by: "Fred Li",
    titleEn: "Advisor actions on top & sector tag control panel",
    titleCn: "顾问操作按钮置顶与行业标签控制面板",
    itemsEn: [
      "Advisor detail dialog — edit, request approval, approve/reject and delete buttons moved from the bottom to the top, right under the header",
      "Admin → Sector tags upgraded into a control panel — assign a colour to each tag from a preset palette; coloured tags show across advisor and partner pages",
      "Reorder tags with up/down arrows — the order applies everywhere tags are listed and filtered",
      "Usage counts per tag — see at a glance how many advisors and partners carry each tag before editing or deleting it",
    ],
    itemsCn: [
      "顾问详情弹窗 — 编辑、发起审批、通过/退回与删除按钮从底部移至顶部，紧贴标题下方",
      "管理后台 → 行业标签升级为控制面板 — 可从预设色板为每个标签指定颜色，并在顾问与伙伴页面生效",
      "上下箭头调整标签顺序 — 顺序在所有标签列表与筛选中统一生效",
      "每个标签显示使用量 — 编辑或删除前一目了然有多少顾问与伙伴使用该标签",
    ],
  },
  {
    version: "5.5.1",
    date: "2026-07-22",
    by: "Ameen Mohd Fairuz",
    titleEn: "Functional email delivery",
    titleCn: "邮件发送功能上线",
    itemsEn: [
      "Email delivery is now functional — registration confirmations and password-reset links are sent through a configurable SMTP mail server",
      "Configurable mail settings (MAIL_SERVER, MAIL_PORT, MAIL_USE_TLS, MAIL_USERNAME, MAIL_PASSWORD, MAIL_DEFAULT_SENDER); the earlier Gmail settings still work",
      "When mail is not configured, features still degrade gracefully — registration succeeds without a confirmation email and reset falls back to secret questions",
    ],
    itemsCn: [
      "邮件发送已可用 — 注册确认与密码重置链接现通过可配置的 SMTP 邮件服务器发送",
      "可配置的邮件设置（MAIL_SERVER、MAIL_PORT、MAIL_USE_TLS、MAIL_USERNAME、MAIL_PASSWORD、MAIL_DEFAULT_SENDER）；原有 Gmail 设置仍然可用",
      "未配置邮件时功能仍优雅降级 — 注册无需确认邮件即可完成，重置回退到密保问题",
    ],
  },
  {
    version: "5.5",
    date: "2026-07-21",
    by: "Fred Li",
    titleEn: "Advisor CRM — sector tags, momentum & approval email",
    titleCn: "顾问CRM — 行业标签、互动热度与审批邮件",
    itemsEn: [
      "Sector tags shared by advisors and domain knowledge partners — filter both lists by sector; tags are managed by admins in the new Admin → Tags tab",
      "Advisor CRM — optional date of birth (DD/MM, year optional), public listing clearance flag (default no), and an internal activities log (meetings, calls, events, notes) per advisor",
      "Momentum indicator — a dot beside each advisor shows engagement freshness (active / warm / dormant) based on the latest logged activity; filter by momentum",
      "One-click approval request email — Gobi-styled email preview addressed to the COO office (configurable in Admin → Settings), cc Fred Li, opens in your mail client",
      "LinkedIn auto-sync — paste a LinkedIn URL on the advisor form and let AI fill name, background, domains and roles; includes a paste-text fallback when LinkedIn blocks fetching",
      "Advisors page now matches the partners page — grid or list view, sort options, display toggles, and sector tag & momentum filters; a team workflow diagram shows the register → fact-check → approval → clearance → public pipeline",
      "Activities, birthdays and momentum stay internal — viewers see none of them, on screen or via the API",
    ],
    itemsCn: [
      "顾问与领域知识伙伴共用行业标签 — 两个列表均可按行业筛选；标签由管理员在“管理后台 → 标签”统一管理",
      "顾问CRM — 可选生日（日/月，年份可留空）、公开展示授权标记（默认否），以及每位顾问的内部互动记录（会议、通话、活动、备注）",
      "互动热度指示 — 顾问姓名旁的圆点根据最近互动显示活跃/温热/沉寂状态，并支持按热度筛选",
      "一键生成审批邮件 — 戈壁风格邮件预览，收件人为COO办公室（可在“管理后台 → 设置”配置），抄送 Fred Li，一键在邮件客户端打开",
      "LinkedIn 自动同步 — 在顾问表单粘贴 LinkedIn 链接，AI 自动填充姓名、背景、领域与职务；LinkedIn 拦截抓取时可改为粘贴文本",
      "顾问页面与伙伴页面看齐 — 卡片/列表视图、排序、显示选项、行业标签与热度筛选；新增团队工作流程图，展示登记 → 核实 → 审批 → 授权 → 公开的流程",
      "互动记录、生日与热度仅限内部 — 浏览者在页面与接口均不可见",
    ],
  },
  {
    version: "5.0",
    date: "2026-07-21",
    by: "Fred Li",
    titleEn: "Advisor Network — people, photos & deep links",
    titleCn: "顾问网络 — 人物、照片与深度互联",
    itemsEn: [
      "New Advisor Network section — honourary advisors, domain knowledge partners and mentors, each with photo, multiple jobs & roles, expert domains, background and Gobi PICs",
      "21 advisors migrated from the team list, fact-checked against official web sources, with photos auto-pulled from university and company profile pages",
      "Organizations that advise us (Esri China (HK), OASA) now live in the partner list with a gold 'Our Domain Knowledge Partner' badge instead of a separate list",
      "Everything is inter-linked — admin console records and update-log entries open the partner page, partner pages show their advisors, and an advisor's organization jumps to the partner record",
      "Photo uploads generate an HD copy and a thumbnail automatically; advisor emails and engagement notes stay visible to staff only",
      "Deep links for sharing — /partner/:id and /advisors/:id open the record directly",
    ],
    itemsCn: [
      "新增顾问网络板块 — 荣誉顾问、领域知识伙伴与导师，包含照片、多重职务、专长领域、背景与戈壁负责人",
      "从团队名单迁移 21 位顾问，逐一对照官方网页核实，并自动从大学及公司官网抓取照片",
      "机构类顾问（Esri中国（香港）、OASA）并入合作伙伴列表，以金色“领域知识伙伴”徽章标识，不再单独维护",
      "全面互联 — 管理后台记录与更新日志可直接打开伙伴页面，伙伴页面展示关联顾问，顾问职务中的机构可跳转至伙伴记录",
      "上传照片自动生成高清版与缩略图；顾问邮箱与合作情况仅团队成员可见",
      "支持深度链接分享 — /partner/:id 与 /advisors/:id 可直接打开对应记录",
    ],
  },
  {
    version: "4.7",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Two-layer regions & interactive star map",
    titleCn: "两层地区分类与可交互星图",
    itemsEn: [
      "Regions now follow a best-practice two-layer model — broad macro-regions (Greater China, Southeast Asia, Northeast Asia, South Asia, Global) each grouping the specific territories, so Southeast Asia correctly includes Singapore, Malaysia, Indonesia, Vietnam and the Philippines",
      "Renamed the old 'International' bucket to 'Global' for anything that cannot be placed in a specific region",
      "The region filter and the star map are now mutually linked — click a region hub on the map to filter to it, and it highlights in gold; clear it and both update together",
      "Fixed a scroll bug where long people-picker lists were cut off at the bottom of the screen on smaller devices",
    ],
    itemsCn: [
      "地区采用最佳实践的两层分类 — 宏观大区（大中华区、东南亚、东北亚、南亚、全球）分别统领具体地区，东南亚现已正确包含新加坡、马来西亚、印尼、越南与菲律宾",
      "将原来的“国际”归类重命名为“全球”，用于无法归入具体地区的伙伴",
      "地区筛选与星图现已双向联动 — 在星图上点击地区节点即可筛选并以金色高亮，取消时两者同步更新",
      "修复在较小屏幕上选择负责人时长列表被屏幕底部截断、无法滚动的问题",
    ],
  },
  {
    version: "4.6",
    date: "2026-07-20",
    by: "Fred Li",
    titleEn: "Updates tabs & smoother rights editing",
    titleCn: "动态双日志与更顺手的权限编辑",
    itemsEn: [
      "Updates page split into two tabs — the system update log (every release, newest first) and a new partnership records log that lists every partner by date, newest first",
      "Admin rights matrix now stages your changes — tick the boxes (they highlight instantly) and save the whole row in one go, instead of a slow save on every click, with a Reset to discard unsaved edits",
      "Removed the duplicate internal-testing note in the bottom corner",
    ],
    itemsCn: [
      "动态页拆分为两个标签 — 系统更新日志（每次发布，最新在前）与全新的合作记录日志（按日期列出每家合作伙伴，最新在前）",
      "管理后台权限矩阵改为暂存式编辑 — 勾选后立即高亮，整行一次性保存，不再每次点击都缓慢保存，并可一键重置放弃未保存的更改",
      "移除右下角重复的内部测试提示",
    ],
  },
  {
    version: "4.5",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Desert scene, R&D planner, display options & rights matrix",
    titleCn: "沙漠场景、研发规划、显示选项与权限矩阵",
    itemsEn: [
      "New Developer R&D Planner — dev/admin-only roadmap of the ecosystem's modules, functions and agents on a date timeline with teammate tags, built to show management",
      "Light mode now opens onto a cinematic Gobi desert — drifting dunes, wind-blown sand and a slow camel caravan with long shadows; dark mode keeps the galaxy",
      "Display options on cards and the star map — toggle NEW, LP star, PIC, region, stage and category blocks before screenshotting as a slide",
      "Admin accounts redesigned as a rights checkbox matrix (View / Edit / IR / Dev / Admin) with a plain-language legend, including the new Developer tag",
      "Admins can edit any member's name, title and photo, and run the gobi.vc sync for them",
      "Roles and network synced from fred-li.vercel.app — updated title and nine new ecosystem partners across HK universities, NUS BLOCK71, BIOCHINA, Tencent Education, RITS, GBA NTIC and LEAP East",
      "Related sites in the footer (gobi.vc and fred-li.vercel.app), and the update log now shows the author of each release",
    ],
    itemsCn: [
      "新增开发者研发规划 — 仅开发者与管理员可见，以时间线展示生态内模块、功能与智能体的建设计划，带团队成员标签，可直接向管理层展示",
      "浅色模式呈现电影感戈壁沙漠 — 沙丘漂移、风沙拂过、驼队缓行并投下长影；深色模式保留星空",
      "卡片与星图新增显示选项 — 截图做幻灯片前可自由隐藏 NEW、LP 星标、负责人、地区、阶段与类别信息块",
      "管理后台账号改为权限勾选矩阵（查看 / 编辑 / IR / 开发 / 管理），含新增的开发者标签，并附通俗易懂的权限说明",
      "管理员可编辑任何成员的姓名、职位与照片，并可代为执行 gobi.vc 同步",
      "角色与网络与 fred-li.vercel.app 同步 — 更新职位，并新增九家生态伙伴（香港高校、NUS BLOCK71、BIOCHINA、腾讯教育、深圳清华研究院、大湾区国创中心、LEAP East）",
      "页脚新增相关网站（gobi.vc 与 fred-li.vercel.app），系统更新日志显示每次发布的作者",
    ],
  },
  {
    version: "4.4",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Galaxy interface",
    titleCn: "星系界面",
    itemsEn: [
      "Animated starry-galaxy background across the portal, including the sign-in screen — twinkling stars, drifting nebulas and the occasional shooting star",
      "Glass interface — cards, dialogs and panels are now slightly translucent with a soft blur so the galaxy shows through",
      "Adapts to light and dark mode, and respects reduced-motion system settings",
    ],
    itemsCn: [
      "全站动态星空背景（含登录页）— 星光闪烁、星云漂移，偶有流星划过",
      "玻璃质感界面 — 卡片、弹窗与面板微透明并带柔和模糊，星空若隐若现",
      "自适应深浅色模式，并遵循系统的减少动效设置",
    ],
  },
  {
    version: "4.3",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "LP status, smarter AI intake & data upgrade",
    titleCn: "LP 状态、更智能的 AI 录入与数据升级",
    itemsEn: [
      "Remember me — stay signed in on this device between visits",
      "One-click profile sync from gobi.vc (photo and title) after registering",
      "Smarter AI intake — detects documents, links or plain text, fetches linked pages, summarises the relationship and suggests the PIC automatically",
      "LP status per partner (N/A / Target LP / LP) — visible only to the IR team, with a new IR-team toggle in admin accounts",
      "Full partnership info upgrade — researched descriptions, PICs, start dates and LP flags across the directory, sourced from gobi.vc and public news",
      "New Advisors section (coming soon) and a portal-wide disclaimer in the footer",
    ],
    itemsCn: [
      "记住我 — 在本设备上保持登录状态",
      "注册后可一键从 gobi.vc 同步个人资料（照片与职位）",
      "更智能的 AI 录入 — 自动识别文档、链接或纯文本，拓展链接内容，总结合作关系并自动建议负责人",
      "合作伙伴 LP 状态（无 / 目标 LP / LP）— 仅 IR 团队可见，管理后台新增 IR 团队开关",
      "合作信息全面升级 — 基于 gobi.vc 与公开报道补充描述、负责人、起始日期与 LP 标识",
      "新增顾问板块（即将上线），并在页脚添加免责声明",
    ],
  },
  {
    version: "4.2",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Filters, feedback & photo galleries",
    titleCn: "筛选、反馈与照片展示",
    itemsEn: [
      "Filters now support selecting multiple options at once (category, stage, region, year)",
      "New Updates page — full system update log plus system requests & feedback",
      "Submit a system request from the portal and track its status (open / in progress / solved / declined)",
      "Admins can reply to requests, manage them in a new admin tab, and add team accounts directly",
      "Search boxes added to the admin console (partnership records and team accounts)",
      "Partner photo carousels — example galleries added for HKU, HKUST and HKIC",
    ],
    itemsCn: [
      "筛选器支持多选（类别、阶段、地区、年份）",
      "新增系统动态页面 — 完整更新日志与系统需求反馈",
      "可在门户内提交系统需求并跟踪处理状态（待处理 / 处理中 / 已解决 / 已拒绝）",
      "管理员可回复需求、在新的管理页签中处理，并可直接新增团队账户",
      "管理后台新增搜索框（合作记录与团队账户）",
      "合作伙伴照片轮播 — 已为港大、科大与港投公司添加示例图库",
    ],
  },
  {
    version: "4.1",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Account security & email",
    titleCn: "账户安全与邮件",
    itemsEn: [
      "Forgot password — reset via an emailed link or by answering secret questions",
      "Secret questions are set during registration (bilingual, answers stored hashed)",
      "Confirmation email sent when registration completes",
      "@gobi.vc registrations are approved automatically as viewers — sign in right away",
    ],
    itemsCn: [
      "忘记密码 — 可通过邮箱重置链接或回答密保问题重置",
      "注册时设置密保问题（中英双语，答案加密存储）",
      "注册完成后自动发送确认邮件",
      "@gobi.vc 邮箱注册自动获批为查看者，无需等待审批",
    ],
  },
  {
    version: "4.0",
    date: "2026-07-15",
    by: "Fred Li",
    titleEn: "Login-first, Gobi rebrand, timeline & audit",
    titleCn: "登录优先、Gobi 品牌升级、时间线与审计",
    itemsEn: [
      "Sign-in is now required before viewing any content",
      "Rebranded to Gobi Partners with the official logo (light/dark)",
      "Partnership stage (01-05) and collaboration level merged — stage is the single source of truth",
      "New timeline view with date-range and year filters",
      "Hall of Fame is now a mode inside the star map, with full filters",
      "Export records to Excel or CSV with selectable fields",
      "Start date is compulsory; AI quick-fill estimates it from documents",
      "AI quick-fill now runs on DeepSeek (PDF / DOCX / text)",
      "NEW badge on entries added within the last month",
      "Lists sorted by strategic level, then alphabetically",
      "Per-partner change log (who changed what, when) for audit",
      "Editable user profiles — title and photo",
      "Edit button in partner details for signed-in staff and admins",
      "Admin table shows PIC and start date columns",
    ],
    itemsCn: [
      "查看任何内容前必须先登录",
      "品牌升级为 Gobi Partners，启用官方标识（明暗两版）",
      "合作阶段（01-05）与协作等级合并 — 以阶段为唯一标准",
      "新增时间线视图，支持日期区间与年份筛选",
      "荣誉殿堂并入星图模式，支持全部筛选条件",
      "支持导出 Excel 或 CSV，可自选字段",
      "开始日期为必填项；AI 速填可从文档中估算",
      "AI 速填改用 DeepSeek（支持 PDF / DOCX / 文本）",
      "近一个月新增条目显示 NEW 标识",
      "列表按战略等级排序，再按字母排序",
      "每个伙伴均有变更记录（谁、何时、改了什么）以供审计",
      "用户可编辑个人资料 — 职位与照片",
      "登录后可在伙伴详情中直接编辑",
      "管理表新增负责人与开始日期列",
    ],
  },
  {
    version: "3.0",
    date: "2026-07-12",
    by: "Fred Li",
    titleEn: "Full partner sync, star map & multi-PIC",
    titleCn: "全量伙伴同步、星图与多负责人",
    itemsEn: [
      "Synchronised the full 55-partner database",
      "Interactive star map (network view) of the partnership ecosystem",
      "Multiple Gobi PICs per partnership with avatar groups",
      "Developer note and internal-testing banner",
    ],
    itemsCn: [
      "同步全部 55 家合作伙伴数据库",
      "合作生态互动星图（网络视图）",
      "每个合作可指定多位戈壁负责人，头像组展示",
      "开发者署名与内部测试横幅",
    ],
  },
  {
    version: "2.0",
    date: "2026-07-10",
    by: "Fred Li",
    titleEn: "Roles, AI quick-fill & attachments",
    titleCn: "角色权限、AI 速填与附件",
    itemsEn: [
      "Admin / staff / viewer roles with approval workflow",
      "AI quick-fill: paste text or upload documents to fill the form",
      "File attachments on partnership records",
      "01-05 partnership stage pipeline",
    ],
    itemsCn: [
      "管理员 / 员工 / 访客角色与审批流程",
      "AI 速填：粘贴文本或上传文档自动填表",
      "合作记录支持文件附件",
      "01-05 合作阶段管道",
    ],
  },
  {
    version: "1.0",
    date: "2026-07-08",
    by: "Fred Li",
    titleEn: "First release — bilingual partnership portal",
    titleCn: "首个版本 — 双语合作伙伴门户",
    itemsEn: [
      "Bilingual (EN/CN) partnership directory with logos and details",
      "Login and admin approval for registering partnerships",
      "Persistent database storage",
      "Cosmic navy / gold / aqua styling after the Li Fo Venture Notes site",
    ],
    itemsCn: [
      "双语（中/英）合作伙伴目录，含标识与详情",
      "登录与管理员审批的合作登记流程",
      "持久化数据库存储",
      "沿用李佛创投笔记网站的深蓝 / 金 / 湖蓝风格",
    ],
  },
];
