// Auto-generated seed data — v3 partner list (2025 Ecosystem Partners doc + Gobi JP/KR/VN expansion)
export const SEED_PARTNERS: any[] = [
  {
    "nameEn": "The University of Hong Kong",
    "lpStatus": "lp",
    "nameCn": "香港大学",
    "category": "university",
    "region": "hongkong",
    "website": "https://www.hku.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hku.hk&sz=128",
    "descriptionEn": "Joint fund partner in HKU's Entrepreneurship Engine Fund (EEF), backing DeepTech spin-offs and research commercialisation.",
    "descriptionCn": "港大创业引擎基金（EEF）联合基金伙伴，支持深科技衍生企业与科研成果转化。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li",
      "Chibo Tang"
    ],
    "partnershipType": "Joint fund — Entrepreneurship Engine Fund (EEF)",
    "startDate": "2024-06-01",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 1,
    "notes": "",
    "context": "Gobi is a joint fund partner in HKU’s Entrepreneurship Engine Fund (EEF), an initiative aimed at fostering innovation and supporting DeepTech startups within the university’s ecosystem. The fund creates a “patient capital” cluster to scale scientific advancements and commercialise research.\n\nLeveraging its expertise in the Greater Bay Area and emerging Asian markets, Gobi plays a key role in nurturing early-stage ventures. Through collaboration with partners such as DEFTA Partners and CASSTAR, Gobi strengthens the region’s innovation pipeline and reinforces its commitment to advancing technological entrepreneurship. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKU Medicine (HKUMed)",
    "nameCn": "香港大学医学院",
    "category": "university",
    "region": "hongkong",
    "website": "https://www.med.hku.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=med.hku.hk&sz=128",
    "descriptionEn": "Faculty-level collaboration under the HKU partnership — biotech and clinical innovation deal flow.",
    "descriptionCn": "港大合作框架下的学院级合作——生物科技与临床创新项目源。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li"
    ],
    "partnershipType": "Faculty collaboration",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "parentId": 1,
    "context": "Sub-partnership of The University of Hong Kong focused on HKUMed spin-offs and clinical innovation."
  },
  {
    "nameEn": "HKUST",
    "lpStatus": "lp",
    "nameCn": "香港科技大学",
    "category": "university",
    "region": "hongkong",
    "website": "https://hkust.edu.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hkust.edu.hk&sz=128",
    "descriptionEn": "Strategic joint innovation fund (Gobi-Redbird) commercialising HKUST research and deep-tech ventures.",
    "descriptionCn": "与香港科技大学共设 Gobi-Redbird 联合创新基金，推动科研成果与深科技项目商业化。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li",
      "Jackson Chung"
    ],
    "partnershipType": "Joint innovation fund — Gobi-Redbird",
    "startDate": "2024-09-01",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 1,
    "notes": "",
    "context": "Gobi serves as the fund manager for the specialized Gobi-Redbird Innovation Fund, an initiative backed by HKUST and HKIC aimed at fostering innovation and supporting early-stage DeepTech startups within the university's ecosystem. The fund creates a dedicated venture capital cluster to scale scientific advancements and commercialise research.\n\nLeveraging its expertise in the Greater Bay Area and emerging Asian markets, Gobi plays a key role in nurturing campus-born ventures. Through active ecosystem collaboration—such as evaluating high-potential startups and mentoring founders at flagship showcases like HKUST Unicorn Day—Gobi strengthens the region’s innovation pipeline and reinforces its commitment to advancing technological entrepreneurship. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "CUHK Innovation Summit",
    "nameCn": "中大创新峰会",
    "category": "university",
    "region": "hongkong",
    "website": "https://cuhkinnovation.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=cuhkinnovation.hk&sz=128",
    "descriptionEn": "MoU partner of CUHK Innovation since the summit's inaugural 2024 edition — supporting early-stage startups and research commercialisation.",
    "descriptionCn": "自2024年首届峰会起与中大创新签署合作备忘录，支持早期初创企业与科研成果转化。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li",
      "Chibo Tang"
    ],
    "partnershipType": "MoU — innovation ecosystem",
    "startDate": "2024-04-25",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "The CUHK Innovation Summit connects investors, ecosystem partners, and academics to drive collaboration and innovation. On 25 April 2024, Gobi reinforced its support for Hong Kong’s innovation ecosystem by signing an MoU with CUHK Innovation during the summit’s inaugural edition.\n\nAs a key partner, Gobi supports early-stage startups and advances research commercialisation through close collaboration with CUHK and fellow investors. The partnership reflects Gobi’s ongoing commitment to empowering entrepreneurship across the region. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "J.P. Morgan",
    "nameCn": "摩根大通",
    "category": "corporate",
    "region": "global",
    "website": "https://www.jpmorgan.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=jpmorgan.com&sz=128",
    "descriptionEn": "Collaboration with J.P. Morgan's Innovation Economy division to accelerate regional startup ecosystems and cross-border investor networks.",
    "descriptionCn": "与摩根大通创新经济部门合作，加速区域创业生态与跨境投资人网络建设。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Chibo Tang",
      "Hing Cheng"
    ],
    "partnershipType": "Innovation economy collaboration",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "J.P. Morgan is a premier global financial services firm delivering market-leading banking solutions worldwide. Through its Innovation Economy division, the firm champions high-growth tech entrepreneurs and venture capitalists, leveraging its global platform to support startups through every phase of their scaling journey.\n\nGobi partners with J.P. Morgan to accelerate the growth of regional startup ecosystems and strengthen cross-border investor networks. The investment team actively engages with the firm’s specialized programs, connecting with high-potential founders at initiatives like the JPM Innovation House to foster strategic fundraising and alignment. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKVCA",
    "nameCn": "香港创业及私募投资协会",
    "category": "investor",
    "region": "hongkong",
    "website": "https://www.hkvca.com.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hkvca.com.hk&sz=128",
    "descriptionEn": "Industry association collaboration — contributing VC insights at the Greater China Private Equity Summit and flagship events.",
    "descriptionCn": "行业协会合作——在大中华区私募股权峰会等旗舰活动分享创投洞见。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Chibo Tang",
      "Eunice Lam"
    ],
    "partnershipType": "Industry association",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Hong Kong Venture Capital and Private Equity Association (HKVCA) is a premier industry body dedicated to promoting and fostering the venture capital and private equity markets in Asia. By creating a vibrant platform for networking, professional development, and advocacy, the Association connects institutional investors, fund managers, and industry advisors to drive market best practices and strengthen Hong Kong’s position as a leading global financial and investment hub.\n\nGobi collaborates with HKVCA to advance regional investment strategies and support ecosystem growth. This includes contributing strategic market insights to the Association's flagship gatherings, notably sharing venture capital perspectives during panel discussions at the prominent Greater China Private Equity Summit. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "VCBeat",
    "nameCn": "动脉网 / VCBeat",
    "category": "media",
    "region": "mainland",
    "website": "https://vcbeat.top",
    "logoUrl": "https://www.google.com/s2/favicons?domain=vcbeat.top&sz=128",
    "descriptionEn": "Healthcare media and research collaboration — panels at VB100 and the China Innovative Medical Assets Parlor.",
    "descriptionCn": "医疗健康媒体与研究合作——参与未来医疗100强大会与中国创新医疗资产会客厅等论坛。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Renee Pan",
      "Berlin Chen"
    ],
    "partnershipType": "Media & research collaboration",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "VCBeat (動脈網) is a leading Chinese media and research platform focused on the healthcare and life sciences innovation sectors. By tracking global industry data, emerging technologies, and policy shifts, the platform provides deep industrial insights and organizes premier medical technology conferences to connect entrepreneurs, research institutions, and specialized investors across the healthcare ecosystem.\n\nGobi collaborates with VCBeat to identify and evaluate breakthrough medical technologies and frontier healthcare solutions. This includes contributing industry-leading insights to the platform's flagship national forums, sharing market perspectives during panel discussions at the China Innovative Medical Assets Parlor (中國創新醫療資產會客廳) and the Future Healthcare VB100 Conference (未來醫療醫藥100強大會). (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKTDC",
    "nameCn": "香港贸易发展局",
    "category": "government",
    "region": "hongkong",
    "website": "https://www.hktdc.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hktdc.com&sz=128",
    "descriptionEn": "Ecosystem collaboration across HKTDC flagship platforms — pitch judging at ASGH and Start-up Express.",
    "descriptionCn": "参与贸发局旗舰平台生态合作——担任亚洲医疗健康高峰论坛及创业快线评审。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li",
      "Hazel Wong"
    ],
    "partnershipType": "Ecosystem — judging & events",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Hong Kong Trade Development Council (HKTDC) is a statutory body established to promote, assist, and develop Hong Kong's trade. Through its global network of offices, the Council organizes international exhibitions, conferences, and business missions to create opportunities for local small and medium-sized enterprises, while positioning Hong Kong as a premier two-way global investment and business hub.\n\nGobi collaborates closely with HKTDC to drive entrepreneurial growth and evaluate breakthrough innovations across its flagship international platforms. This includes providing strategic guidance and venture capital expertise to global cohorts, notably serving as pitch judges during the Asia Summit on Global Health (ASGH) as well as evaluating high-potential tech startups at the annual HKTDC Start-up Express Pitching Final. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKIC",
    "lpStatus": "lp",
    "nameCn": "香港投资管理有限公司",
    "category": "investor",
    "region": "hongkong",
    "website": "https://www.hkic.org.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hkic.org.hk&sz=128",
    "descriptionEn": "Strategic alignment with HKIC's patient capital — backing the Gobi-Redbird Fund and deep-tech commercialisation in Hong Kong.",
    "descriptionCn": "与香港投资管理公司耐心资本协同——支持 Gobi-Redbird 基金与香港深科技成果转化。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Chibo Tang",
      "Fred Li"
    ],
    "partnershipType": "Strategic capital partner",
    "startDate": "",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Hong Kong Investment Corporation Limited (HKIC) is a government-owned institutional investor that deploys strategic capital into Hong Kong's innovation and technology sectors. Focusing on core areas like artificial intelligence, biotechnology, and green technology, HKIC invests patient capital to enhance the city's competitiveness, drive economic value, and attract global investment into the regional ecosystem.\n\nGobi works in tandem with HKIC to anchor frontier technologies and accelerate the commercialization of deep-tech clusters within the local ecosystem. This synergy is demonstrated through active participation in specialized industry plug-ins, such as the Large Model Industry Forum co-hosted with the Beijing Academy of Artificial Intelligence (BAAI), where Gobi helps bridge high-caliber research with market-ready applications to build a robust regional AI value chain. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Phoenix TV",
    "nameCn": "凤凰卫视",
    "category": "media",
    "region": "hongkong",
    "website": "https://www.phoenixtv.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=phoenixtv.com&sz=128",
    "descriptionEn": "Media collaboration — VC perspectives at the Phoenix Bay Area Financial Forum and Phoenix Summit.",
    "descriptionCn": "媒体合作——在凤凰湾区财经论坛及凤凰峰会分享创投观点。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Hazel Wong"
    ],
    "partnershipType": "Media collaboration",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Phoenix TV is a leading global Chinese-language media network that provides comprehensive news, business analysis, and cultural programming to audiences across more than 180 countries and regions. Leveraging its strong media presence, the network serves as a vital bridge for economic communication, hosting high-profile international forums to foster regional collaboration and financial integration within the Greater Bay Area.\n\nGobi supports Phoenix TV by providing expert venture capital perspectives for its premier economic and financial broadcasts. Gobishares strategic insights on regional innovation and economic development, notably serving as panel speakers during the Phoenix GBA Financial Forum and Summit. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "CFA Society Hong Kong",
    "nameCn": "香港特许金融分析师学会",
    "category": "ecosystem",
    "region": "hongkong",
    "website": "https://www.cfasocietyhongkong.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=cfasocietyhongkong.org&sz=128",
    "descriptionEn": "Thought leadership for CFA Society Hong Kong programmes, including the 2026 Sustainable Investing Symposium.",
    "descriptionCn": "为香港特许金融分析师学会旗舰项目提供思想领导力，包括2026可持续投资研讨会。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li"
    ],
    "partnershipType": "Thought leadership",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "CFA Society Hong Kong is a professional organization comprising local financial analysts and investment professionals. Dedicated to promoting the highest ethical and professional standards within the region’s financial industry, the Society supports the investment community through continuous education, networking, and market advocacy.\n\nGobi supports CFA Society Hong Kong by contributing thought leadership and investment insights to its flagship financial programs. The investment team actively participates in high-profile industry dialogues, such as the 2026 Sustainable Investing Symposium, to share venture capital perspectives and advance regional ESG and sustainable investment outcomes. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKSTP",
    "nameCn": "香港科技园",
    "category": "government",
    "region": "hongkong",
    "website": "https://www.hkstp.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hkstp.org&sz=128",
    "descriptionEn": "Long-standing ecosystem ally — investor readiness workshops and joint initiatives such as GreenTech Connect.",
    "descriptionCn": "长期生态伙伴——投资人就绪工作坊及 GreenTech Connect 等联合项目。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jackson Chung",
      "Fred Li"
    ],
    "partnershipType": "Deal flow MOU",
    "startDate": "2025-03-15",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "As a long-standing ecosystem ally, Gobi Partners works with HKSTP to bridge the gap between capital and research commercialization, collaborating on joint funding initiatives, accelerator programmes, and regional pitching events to scale local startups into the international market.\n\nGobi supports HKSTP by delivering specialized investor readiness and corporate structuring workshops for its technology community. Gobi contributes to joint ecosystem initiatives like the \"GreenTech Connect\" workshop, providing venture capital insights to bridge the gap between sustainability-driven innovation and financial backing. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Citi",
    "nameCn": "花旗集团",
    "category": "corporate",
    "region": "global",
    "website": "https://www.citigroup.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=citigroup.com&sz=128",
    "descriptionEn": "Thought-leadership collaboration via Citi industry panels on next-generation fintech.",
    "descriptionCn": "通过花旗行业论坛开展思想领导力合作，聚焦新一代金融科技。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Hing Cheng"
    ],
    "partnershipType": "Thought leadership",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Gobi actively collaborates with Citi through targeted industry panels, an initiative aimed at fostering innovation and supporting high-growth startups within the regional ecosystem. The collaboration creates a vibrant dialogue cluster to scale market insights and commercialise next-generation financial technologies.\n\nLeveraging its expertise in the Greater Bay Area and emerging Asian markets, Gobi plays a key role in nurturing early-stage ventures alongside global financial institutions. Through participating in dedicated thought-leadership events like the Citi Panel, Gobi strengthens the region’s innovation pipeline and reinforces its commitment to advancing technological entrepreneurship. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "HKGCYE",
    "nameCn": "香港青年创业家总商会",
    "category": "ecosystem",
    "region": "hongkong",
    "website": "https://www.hkgcye.org.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=hkgcye.org.hk&sz=128",
    "descriptionEn": "Corporate finance workshops and ecosystem mentorship for young entrepreneurs in Hong Kong.",
    "descriptionCn": "为香港青年创业者提供企业融资工作坊与生态导师指导。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li"
    ],
    "partnershipType": "Ecosystem & mentorship",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Hong Kong General Chamber of Young Entrepreneurs (HKGCYE) is a leading platform dedicated to fostering the next generation of entrepreneurial leaders in Hong Kong. Focusing on professional training, resource networking, and cross-border market access within the Greater Bay Area, the Chamber empowers young founders with the tools required to scale their ventures efficiently.\n\nGobi supports HKGCYE by delivering corporate finance and fundraising workshops for its young entrepreneur community. The investment team also provides ecosystem mentorship to guide early-stage founders on navigating angel investments. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "GIIC",
    "nameCn": "菲律宾性别视角与影响力投资委员会",
    "category": "investor",
    "region": "philippines",
    "website": "https://giicph.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=giicph.com&sz=128",
    "descriptionEn": "Founding member of the Philippines' Gender Lens & Impact Investment Council.",
    "descriptionCn": "菲律宾性别视角与影响力投资委员会创始成员。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar",
      "Jason Gaisano"
    ],
    "partnershipType": "Founding member",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Gender Lens & Impact Investment Council (GIIC) is a Philippines-based industry body focused on strengthening the gender lens and impact investment ecosystem to unlock capital for local entrepreneurs.\n\nAs a founding member, Gobi works closely with women’s advocacy groups and government stakeholders to promote the empowerment of women entrepreneurs and workers. The fund also contributes as an ecosystem partner in GIIC’s initiatives, including dialogues on impact investing and inclusive growth. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "GUIDE",
    "nameCn": "GUIDE 创始人学院",
    "category": "accelerator",
    "region": "malaysia",
    "website": "https://www.guide.works",
    "logoUrl": "https://www.google.com/s2/favicons?domain=guide.works&sz=128",
    "descriptionEn": "Gobi co-founder Thomas G. Tsao serves as GUIDE's Founding Chair; portfolio founders join as speakers and mentors.",
    "descriptionCn": "Gobi 联合创始人曹嘉泰担任 GUIDE 创始主席，组合公司创始人担任讲者与导师。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao",
      "Jamaludin Bujang"
    ],
    "partnershipType": "Founders' programme — Founding Chair",
    "startDate": "",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "GUIDE is a venture-education platform dedicated to supporting entrepreneurs and strengthening startup ecosystems, with a focus on public–private collaboration. Its flagship initiative, the 12-month GUIDE Founders’ Programme, supports early-stage entrepreneurs across Asia at the zero-to-one stage.\n\nGobi actively contributes to GUIDE by connecting portfolio founders as speakers and mentors. Thomas Tsao, Gobi’s Co-Founder, also serves as GUIDE’s Founding Chair—reinforcing the fund’s commitment to ecosystem development through education and regional partnerships. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Khazanah Nasional",
    "nameCn": "马来西亚国库控股",
    "category": "government",
    "region": "malaysia",
    "website": "https://www.khazanah.com.my",
    "logoUrl": "https://www.google.com/s2/favicons?domain=khazanah.com.my&sz=128",
    "descriptionEn": "Investment partner under the Dana Impak mandate — managing the Gobi Dana Impak Fund for Malaysia's development agenda.",
    "descriptionCn": "Dana Impak 计划投资伙伴——管理 Gobi Dana Impak 基金，支持马来西亚国家发展议程。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jamaludin Bujang",
      "Thomas G. Tsao"
    ],
    "partnershipType": "Gobi Dana Impak Fund",
    "startDate": "",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "Khazanah Nasional is Malaysia’s sovereign wealth fund, tasked with delivering long-term sustainable value by investing in catalytic sectors and building vibrant communities to benefit the nation.\n\nAs an investment partner under the Dana Impak initiative, Gobi contributes to Malaysia’s development through the Gobi Dana Impak Fund. This partnership supports Khazanah’s efforts to drive socioeconomic progress via cross-sector collaboration and strategic capital allocation. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Belt and Road Summit",
    "nameCn": "一带一路高峰论坛",
    "category": "ecosystem",
    "region": "hongkong",
    "website": "https://www.beltandroadsummit.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=beltandroadsummit.com&sz=128",
    "descriptionEn": "MoU platform — signed with Base Therapeutics at the 2024 Summit on gene-editing innovation.",
    "descriptionCn": "合作备忘录平台——2024年峰会期间与倍捷锐就基因编辑创新签署合作备忘录。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li",
      "Hazel Wong"
    ],
    "partnershipType": "Summit MoU platform",
    "startDate": "2024-09-11",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Belt and Road Summit is a leading international platform that promotes multilateral business collaboration among governments and private sector leaders across Belt and Road economies.\n\nAt the 2024 summit, Gobi Partners GBA signed a Memorandum of Understanding with Base Therapeutics to support its advancements in gene editing and healthcare innovation. The partnership reinforces Gobi’s commitment to backing frontier technologies and strengthens its position in global healthcare investment. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "NDC Philippines",
    "nameCn": "菲律宾国家开发公司",
    "category": "government",
    "region": "philippines",
    "website": "https://www.ndc.gov.ph",
    "logoUrl": "https://www.google.com/s2/favicons?domain=ndc.gov.ph&sz=128",
    "descriptionEn": "Co-Investment Partner to the Startup Venture Fund since 2023; 2025 MOU on the Philippine Innovation Hub.",
    "descriptionCn": "自2023年起担任创业风险基金联合投资伙伴，并于2025年就菲律宾创新中心签署合作备忘录。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jason Gaisano",
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "SVF co-investment partner",
    "startDate": "2023-06-01",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "The National Development Company (NDC) is the state-owned investment arm of the Philippines, supporting industrial and innovation-led growth through initiatives such as the Startup Venture Fund (SVF).\n\nSince 2023, Gobi-Core has served as a Co-Investment Partner to the SVF, matching investments in qualified Philippine-based startups. Beyond capital, Gobi contributes mentorship, oversight, and network access. In 2025, Gobi signed a MOU with NDC to strengthen support for the Philippine Innovation Hub (iHub). (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Philippine Startup Week",
    "nameCn": "菲律宾创业周",
    "category": "ecosystem",
    "region": "philippines",
    "website": "https://www.phstartupweek.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=phstartupweek.com&sz=128",
    "descriptionEn": "Key partner of the Philippines' flagship startup week — thought leadership and Fiestartup co-organiser.",
    "descriptionCn": "菲律宾旗舰创业周核心伙伴——贡献思想领导力并联合主办 Fiestartup。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jason Gaisano",
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Conference partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Philippine Startup Week is the country’s flagship annual startup conference, held every November to showcase high-potential Filipino startups and foster collaboration across the innovation ecosystem.\n\nGobi-Core is a key partner of PHSW, contributing thought leadership through initiatives such as the Philippine Horizons: Filipino Innovation in the ASEAN Landscape report. The fund also co-organises Fiestartup, a grassroots initiative that supports and celebrates the startup ecosystem in Cebu. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "She Loves Tech",
    "nameCn": "她爱科技",
    "category": "accelerator",
    "region": "singapore",
    "website": "https://www.shelovestech.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=shelovestech.org&sz=128",
    "descriptionEn": "Regular collaborator since 2019 — mentors, judges and co-organisers across ASEAN and China.",
    "descriptionCn": "自2019年起长期合作——在东盟与中国担任导师、评审及联合主办方。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Kay-Mok Ku",
      "Dan Chong"
    ],
    "partnershipType": "Competition partner",
    "startDate": "2019-01-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "She Loves Tech is the world’s largest startup competition for women in technology, operating in over 50 countries to provide advocacy and capacity-building for women-led businesses.\n\nSince 2019, Gobi has been a regular collaborator with SLT, contributing as mentors, judges, and co-organisers across competitions in ASEAN and China—reinforcing the fund’s commitment to gender inclusion in tech entrepreneurship. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Sunway iLabs",
    "nameCn": "双威创新实验室",
    "category": "accelerator",
    "region": "malaysia",
    "website": "https://innovationlabs.sunway.edu.my",
    "logoUrl": "https://www.google.com/s2/favicons?domain=innovationlabs.sunway.edu.my&sz=128",
    "descriptionEn": "Venture partner of LaunchX, Sunway iLabs' university startup accelerator, since 2023.",
    "descriptionCn": "自2023年起担任双威创新实验室 LaunchX 大学创业加速器风险合伙人。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jamaludin Bujang",
      "Hisham Ibrahim"
    ],
    "partnershipType": "LaunchX venture partner",
    "startDate": "2023-01-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Sunway iLabs is a joint initiative by Sunway Group and Sunway University that fosters entrepreneurship and market-driven innovation through collaborative efforts across academia, research, and industry. Its Sunway Living Lab focuses on six key verticals: Smart Cities, Edutech, Digital HealthTech, Agri-food Tech, Retail Tech, and FinTech.\n\nSince 2023, Gobi has supported LaunchX, Sunway iLabs’ university startup accelerator, as a venture partner. The programme equips Malaysian students with the tools and mentorship to transform ideas into fundable startups, contributing to a vibrant pipeline of innovation-driven ventures. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "The Circulars Accelerator",
    "nameCn": "循环经济加速器",
    "category": "accelerator",
    "region": "global",
    "website": "https://www.weforum.org/stories/2021/01/the-circulars-accelerator/",
    "logoUrl": "https://www.google.com/s2/favicons?domain=weforum.org&sz=128",
    "descriptionEn": "Investor partner of The Circulars Accelerator since 2022, backing circular-economy innovators.",
    "descriptionCn": "自2022年起担任循环经济加速器投资伙伴，支持循环经济创新者。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Investor partner",
    "startDate": "2022-01-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Circulars Accelerator is a global programme backed by a network of leading organisations committed to scaling solutions that advance the Circular Economy.\n\nSince 2022, Gobi has been an investor partner of TCA, forming strategic partnerships with circular innovators, amplifying their visibility, and contributing to high-profile events that promote sustainable innovation across the ecosystem. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "The Earthshot Prize",
    "nameCn": "为地球奋斗奖",
    "category": "ecosystem",
    "region": "global",
    "website": "https://earthshotprize.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=earthshotprize.org&sz=128",
    "descriptionEn": "Official Nominator for The Earthshot Prize since 2023.",
    "descriptionCn": "自2023年起担任'为地球奋斗奖'官方提名机构。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Official Nominator",
    "startDate": "2023-01-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Founded by His Royal Highness Prince William in 2020, The Earthshot Prize is a global environmental award that identifies and scales innovative solutions to the world’s most pressing environmental challenges.\n\nSince 2023, Gobi has served as an Official Nominator for TEP, reinforcing its commitment to sustainability leadership across Asia. The fund nominates impactful startups that are developing solutions to regenerate the planet and drive measurable environmental progress. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Twin Towers Ventures",
    "nameCn": "双峰塔创投",
    "category": "investor",
    "region": "malaysia",
    "website": "https://www.ttv.vc",
    "logoUrl": "https://www.google.com/s2/favicons?domain=ttv.vc&sz=128",
    "descriptionEn": "MOU with PETRONAS' venture arm — deal-flow sharing, co-investment and technology commercialisation.",
    "descriptionCn": "与马来西亚国家石油创投部门签署备忘录——共享项目源、联合投资与技术商业化。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jamaludin Bujang",
      "Thomas G. Tsao"
    ],
    "partnershipType": "MOU — co-investment & deal flow",
    "startDate": "2023-09-19",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "Twin Towers Ventures is the investment arm of PETRONAS Ventures, focused on backing early- to growth-stage entrepreneurs across Asia Pacific, the Middle East, and North Africa.\n\nOn 19 September 2023, Gobi signed a Memorandum of Understanding with TTV to promote sustainable innovation in Southeast Asia and the Greater Bay Area. The partnership enables both parties to share deal flow, co-invest in promising ventures, and explore the co-development and commercialisation of PETRONAS’ in-house technologies. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "MYStartup",
    "nameCn": "MYStartup 国家创业平台",
    "category": "government",
    "region": "malaysia",
    "website": "https://mystartup.gov.my",
    "logoUrl": "https://www.google.com/s2/favicons?domain=mystartup.gov.my&sz=128",
    "descriptionEn": "Private partner of Malaysia's national startup platform, powered by Cradle Fund.",
    "descriptionCn": "马来西亚国家创业平台私营伙伴（由 Cradle Fund 运营）。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Hisham Ibrahim",
      "Jamaludin Bujang"
    ],
    "partnershipType": "National platform partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "MYStartup is Malaysia’s national startup platform, initiated by the Ministry of Science, Technology and Innovation (MOSTI) and powered by Cradle Fund, to connect startups with funding, mentorship, talent, and growth opportunities.\n\nGobi is one of the private partners supporting MYStartup’s mission to build a thriving, innovation-led ecosystem. The fund contributes by fostering cross-border collaboration, bridging diverse cultures, and helping local startups scale beyond Malaysia’s borders. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "UpLink",
    "nameCn": "世界经济论坛 UpLink",
    "category": "ecosystem",
    "region": "global",
    "website": "https://uplink.weforum.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=uplink.weforum.org&sz=128",
    "descriptionEn": "Partner on WEF UpLink sustainability challenges, including Traceability for Circularity.",
    "descriptionCn": "世界经济论坛 UpLink 可持续挑战合作伙伴，包括循环追溯创新挑战。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Innovation challenge partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "UpLink is an open innovation platform by the World Economic Forum, developed in partnership with Salesforce and global collaborators to advance solutions aligned with the UN Sustainable Development Goals.\n\nGobi supports UpLink’s sustainability initiatives, including the Traceability for Circularity Challenge, which promotes circular business models through material tracking innovations. The fund is also an active partner of The Circulars Acceleration Network, helping connect startups and corporates to scale Circular Economy solutions globally. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Startup World Cup Malaysia",
    "nameCn": "创业世界杯马来西亚站",
    "category": "ecosystem",
    "region": "malaysia",
    "website": "https://growthcharger.com/startupworldcupmalaysia",
    "logoUrl": "https://www.google.com/s2/favicons?domain=growthcharger.com&sz=128",
    "descriptionEn": "Supporting Partner of Startup World Cup Malaysia since 2023.",
    "descriptionCn": "自2023年起担任创业世界杯马来西亚站支持伙伴。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Hisham Ibrahim",
      "Jamaludin Bujang"
    ],
    "partnershipType": "Supporting partner",
    "startDate": "2023-01-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Startup World Cup Malaysia, organised by Growth Charger and supported by Cradle Fund, is the local edition of a global competition that connects top startups, investors, and tech leaders from over 60 countries. Winners compete at the Grand Finale in San Francisco for a US$1 million investment prize.\n\nSince 2023, Gobi has served as a Supporting Partner, working with Growth Charger to strengthen Malaysia’s startup ecosystem. The fund contributes resources, mentorship, and network access to help local startups scale and compete on the global stage. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "MIECF",
    "nameCn": "澳门国际环保合作发展论坛及展览",
    "category": "government",
    "region": "macau",
    "website": "https://www.macaomiecf.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=macaomiecf.com&sz=128",
    "descriptionEn": "MoU signed at MIECF with Chazence and AB Builders following a RM10M+ co-led round.",
    "descriptionCn": "在澳门国际环保展与 Chazence 及 AB Builders 签署合作备忘录，此前联合领投逾千万令吉融资。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar",
      "Renee Pan"
    ],
    "partnershipType": "MoU at forum",
    "startDate": "2025-03-27",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Macao International Environmental Co-operation Forum & Exhibition (MIECF) is a regional platform hosted by the Macao SAR Government and supported by multiple ministries of the People’s Republic of China. It promotes environmental cooperation and green innovation across the Pan-Pearl River Delta Region.\n\nAt MIECF, Gobi signed a Memorandum of Understanding with ZENCE OBJECT TECH (Chazence) and AB Builders following a strategic financing round of over RM10 million co-led by Gobi and AB Builders. The partnership focuses on scaling Chazence’s eco-friendly materials into international markets. With ISCC PLUS certification and significant market demand, the collaboration reflects Gobi’s commitment to advancing sustainable technology and global market expansion. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "The Liveability Challenge",
    "nameCn": "宜居挑战赛",
    "category": "ecosystem",
    "region": "singapore",
    "website": "https://theliveabilitychallenge.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=theliveabilitychallenge.org&sz=128",
    "descriptionEn": "Three consecutive years on the e-coaching and pitch-preparation committee.",
    "descriptionCn": "连续三年参与辅导与路演准备委员会。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar",
      "Dan Chong"
    ],
    "partnershipType": "Coaching committee",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Liveability Challenge is a regional sustainability initiative that supports Asia-based innovators in developing climate-positive solutions to address pressing urban and environmental challenges.\n\nGobi has participated in the Challenge for three consecutive years, serving on the e-coaching and pitch preparation committee to support startups in refining their solutions and strengthening their investment readiness. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "DICT Philippines",
    "nameCn": "菲律宾信息与通信技术部",
    "category": "government",
    "region": "philippines",
    "website": "https://dict.gov.ph",
    "logoUrl": "https://www.google.com/s2/favicons?domain=dict.gov.ph&sz=128",
    "descriptionEn": "Startup Grant Fund Committee member; 2025 MOU on skills development and startup competitiveness.",
    "descriptionCn": "创业资助基金委员会成员，2025年就技能发展与创业竞争力签署合作备忘录。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jason Gaisano",
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "MOU — SGF committee",
    "startDate": "2025-01-01",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Department of Information and Communications Technology (DICT) supports early-stage innovation in the Philippines through the Startup Grant Fund (SGF), which targets startups from ideation to minimum viable product stage.\n\nAs a member of the SGF Committee, Gobi evaluates business proposals and provides guidance and feedback to founders—contributing to the development of the country’s startup ecosystem. In 2025, Gobi signed an MOU with DICT, focusing on skills development, employability, and capacity building to prepare Filipino startups for local and international competitiveness. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Echelon Philippines",
    "nameCn": "Echelon 菲律宾峰会",
    "category": "ecosystem",
    "region": "philippines",
    "website": "https://e27.co/echelon/philippines/",
    "logoUrl": "https://www.google.com/s2/favicons?domain=e27.co&sz=128",
    "descriptionEn": "Thought leadership at Echelon Philippines — keynote and e-commerce panel at the 2024 inaugural event.",
    "descriptionCn": "在 Echelon 菲律宾峰会贡献思想领导力——2024年首届活动发表主旨演讲并主持电商论坛。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jason Gaisano"
    ],
    "partnershipType": "Conference thought leadership",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Echelon Philippines is a regional platform designed to empower the local startup ecosystem and connect founders, investors, and business leaders across Southeast Asia.\n\nAt its inaugural event in September 2024, Gobi supported the initiative through thought leadership—delivering a keynote on emerging startup trends and moderating a panel on the future of Filipino e-commerce. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Alibaba Global Initiatives",
    "nameCn": "阿里巴巴全球倡议",
    "category": "corporate",
    "region": "mainland",
    "website": "https://agi.alibaba.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=agi.alibaba.com&sz=128",
    "descriptionEn": "Long-time AGI partner — Netpreneur Masterclass Philippines and the AInnovator Program.",
    "descriptionCn": "阿里巴巴全球化项目长期伙伴——菲律宾创业者大师班与 AInnovator 项目。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Renee Pan",
      "Jason Gaisano"
    ],
    "partnershipType": "Netpreneur Masterclass partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Alibaba Global Initiatives is the professional training arm of the eWTP initiative, which is part of Alibaba International Digital Commerce Group (AIDC). Gobi is a long-time partner of AGI, organising events like the Alibaba Netpreneur Masterclass in the Philippines to train entrepreneurs and strengthen connections across the ecosystem. The firm also helped bring in participants for AGI’s AInnovator Program and collaborates on other projects focused on upskilling entrepreneurs and serving the needs of founders. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Investors for Climate (I4C)",
    "nameCn": "气候投资者联盟",
    "category": "investor",
    "region": "singapore",
    "website": "https://www.investorsforclimate.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=investorsforclimate.com&sz=128",
    "descriptionEn": "Partner Carlo Chen-Delantar serves as I4C's Manila ambassador; I4C launched in Manila in November 2025.",
    "descriptionCn": "合伙人 Carlo Chen-Delantar 担任 I4C 马尼拉大使；I4C 于2025年11月落地马尼拉。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Ambassador — climate investing",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Gobi Partner and Head of Sustainability Carlo Chen-Delantar serves as the Manila ambassador to Investors for Climate (I4C), running events to spark conversations on climate investment. I4C is a close-knit community of more than 400 investors across over 40 countries whose members have invested more than US$50 million in climate and sustainability.\n\nI4C launched in Manila in November 2025, creating a new platform for discussions on strengthening the country’s emerging climate-tech ecosystem. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "APCER",
    "nameCn": "亚太循环经济圆桌会议",
    "category": "ecosystem",
    "region": "taiwan",
    "website": "https://www.apcer.asia",
    "logoUrl": "https://www.google.com/s2/favicons?domain=apcer.asia&sz=128",
    "descriptionEn": "Community partner of the 2025 Asia Pacific Circular Economy Roundtable.",
    "descriptionCn": "2025亚太循环经济圆桌会议社区伙伴。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Carlo Chen-Delantar"
    ],
    "partnershipType": "Community partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Gobi attended the 2025 Asia Pacific Circular Economy Roundtable as a community partner. The Asia Pacific Circular Economy Roundtable (APCER) brings together entrepreneurs, corporates, academic experts, advocates, and government leaders to accelerate circular solutions across the Asia Pacific. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Endeavor Pakistan",
    "nameCn": "Endeavor 巴基斯坦",
    "category": "ecosystem",
    "region": "pakistan",
    "website": "https://pakistan.endeavor.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=pakistan.endeavor.org&sz=128",
    "descriptionEn": "Founding board member of Endeavor Pakistan — strategic guidance and selection panels.",
    "descriptionCn": "Endeavor 巴基斯坦创始董事会成员——提供战略指导并参与遴选评审。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Ali Mukhtar",
      "Naiel Ikram"
    ],
    "partnershipType": "Founding board member",
    "startDate": "",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "Endeavor is a global network that supports high-impact entrepreneurs in building thriving ecosystems across emerging and underserved markets.\n\nGobi is a founding board member of Endeavor Pakistan, contributing strategic guidance and participating in investment selection panels—reinforcing its commitment to scaling transformative ventures in the region. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Bank of Punjab",
    "nameCn": "旁遮普银行",
    "category": "government",
    "region": "pakistan",
    "website": "https://www.bop.com.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=bop.com.pk&sz=128",
    "descriptionEn": "MOU on startup financing — preferential debt, equity investment and credit facilities.",
    "descriptionCn": "创业融资合作备忘录——优惠债务融资、股权投资与信贷支持。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Ali Mukhtar",
      "Kashaf Jamal"
    ],
    "partnershipType": "MOU — startup financing",
    "startDate": "",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "The Bank of Punjab is one of Pakistan’s largest publicly listed financial institutions, offering a wide range of banking services across the country.\n\nGobi signed a Memorandum of Understanding with the Bank to establish a framework for supporting entrepreneurship in Pakistan. The partnership includes debt financing at preferential rates, equity investments, and access to credit facilities for startups and founders. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "JazzCash",
    "nameCn": "JazzCash 移动钱包",
    "category": "corporate",
    "region": "pakistan",
    "website": "https://www.jazzcash.com.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=jazzcash.com.pk&sz=128",
    "descriptionEn": "MOU to integrate portfolio companies into Pakistan's leading mobile wallet.",
    "descriptionCn": "合作备忘录——将组合公司接入巴基斯坦领先的移动钱包平台。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Naiel Ikram"
    ],
    "partnershipType": "MOU — platform integration",
    "startDate": "",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "JazzCash, Pakistan’s leading mobile wallet service, is an initiative by Jazz, the country’s largest telecom operator, with over 17 million active users.\n\nGobi signed a Memorandum of Understanding with JazzCash to promote entrepreneurship and integrate portfolio companies into the platform—enabling startups to reach new users while delivering added value to JazzCash customers. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Katalyst Labs",
    "nameCn": "Katalyst 实验室",
    "category": "accelerator",
    "region": "pakistan",
    "website": "https://katalystlabs.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=katalystlabs.pk&sz=128",
    "descriptionEn": "Sponsor of ecosystem events; office hours and workshops for the startup community.",
    "descriptionCn": "赞助生态活动，为创业社区提供辅导时间与工作坊。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Kashaf Jamal"
    ],
    "partnershipType": "Ecosystem sponsor",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Katalyst Labs is a technology accelerator and innovation hub in Pakistan that supports visionary founders through its startup acceleration programme, women entrepreneur fellowship, and ecosystem-focused knowledge sessions.\n\nGobi supports Katalyst Labs by sponsoring ecosystem events and international conferences, as well as conducting office hours and workshops for its startup community. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Habib University",
    "nameCn": "哈比卜大学",
    "category": "university",
    "region": "pakistan",
    "website": "https://habib.edu.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=habib.edu.pk&sz=128",
    "descriptionEn": "Workshops on launching and fundraising for high-tech ventures; student office hours.",
    "descriptionCn": "高科技创业与融资工作坊，并为学生提供辅导时间。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Ali Mukhtar"
    ],
    "partnershipType": "Workshops & office hours",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Habib University is a leading liberal arts and sciences institution in Karachi, committed to enriching student lives and advancing society through teaching, research, and service.\n\nGobi supports Habib University’s entrepreneurial efforts by delivering workshops on launching and fundraising for high-tech ventures. The investment team also provides office hours to guide students on their startup journeys. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "IBA Karachi",
    "nameCn": "卡拉奇工商管理学院",
    "category": "university",
    "region": "pakistan",
    "website": "https://www.iba.edu.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=iba.edu.pk&sz=128",
    "descriptionEn": "Entrepreneurship and fundraising workshops plus office hours at IBA Karachi.",
    "descriptionCn": "为卡拉奇工商管理学院提供创业与融资工作坊及学生辅导时间。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Kashaf Jamal"
    ],
    "partnershipType": "Workshops & office hours",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Institute of Business Administration is a leading business school in Karachi, committed to enriching student lives and advancing society through teaching, research, and service.\n\nGobi supports IBA’s entrepreneurial efforts by delivering workshops on launching and fundraising for high-tech ventures. The investment team also provides office hours to guide students on their startup journeys. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "PakLaunch",
    "nameCn": "PakLaunch 创业社区",
    "category": "ecosystem",
    "region": "pakistan",
    "website": "https://paklaunch.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=paklaunch.com&sz=128",
    "descriptionEn": "Co-host of diaspora-investor meetups connecting Pakistani founders with global capital.",
    "descriptionCn": "联合主办侨民投资人聚会，连接巴基斯坦创始人与全球资本。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Naiel Ikram"
    ],
    "partnershipType": "Community co-host",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "PakLaunch is a global community that connects the Pakistani diaspora with the country’s entrepreneurial and investment ecosystem.\n\nGobi has partnered with PakLaunch on multiple occasions to co-host meetups in Pakistan, fostering connections between local founders and global investors to strengthen cross-border collaboration. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "LUMS LCE",
    "nameCn": "拉合尔管理科学大学创业中心",
    "category": "accelerator",
    "region": "pakistan",
    "website": "https://lce.lums.edu.pk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=lce.lums.edu.pk&sz=128",
    "descriptionEn": "Mentorship partner supporting incubatees at the LUMS Centre for Entrepreneurship.",
    "descriptionCn": "拉合尔管理科学大学创业中心导师伙伴，支持在孵项目。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Ali Mukhtar"
    ],
    "partnershipType": "Mentorship partner",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "LCE, originally established as a campus incubator, has grown into a dynamic platform that connects entrepreneurs, mentors, and industry leaders globally.\n\nGobi partners with LCE to support its entrepreneurial initiatives and provides mentorship to incubatees, reinforcing its commitment to nurturing talent from one of Pakistan’s leading academic institutions. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "National Incubation Centers (NICs)",
    "nameCn": "巴基斯坦国家孵化中心",
    "category": "accelerator",
    "region": "pakistan",
    "website": "https://nickarachi.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=nickarachi.com&sz=128",
    "descriptionEn": "Mentorship, investor summits and pitch competitions across Pakistan's six National Incubation Centers.",
    "descriptionCn": "参与巴基斯坦六大国家孵化中心的导师指导、投资峰会与路演竞赛。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Ali Mukhtar",
      "Kashaf Jamal"
    ],
    "partnershipType": "Mentorship & summits",
    "startDate": "",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "Ignite’s National Incubation Centers (NICs), located across six major cities in Pakistan, have supported over 1,300 startups and empowered more than 2,300 women entrepreneurs to date.\n\nSince the programme’s inception, Gobi has played an active role by providing mentorship and participating in investor summits, pitch competitions, and workshops—contributing to the growth of Pakistan’s startup ecosystem nationwide. (Source: 2025 Ecosystem Partners)"
  },
  {
    "nameEn": "Cyberport",
    "nameCn": "数码港",
    "category": "accelerator",
    "region": "hongkong",
    "website": "https://www.cyberport.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=cyberport.hk&sz=128",
    "descriptionEn": "Co-investment and startup referral agreement with Cyberport ventures team.",
    "descriptionCn": "与数码港创投团队的联合投资与项目推荐协议。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Rosa Dai"
    ],
    "partnershipType": "Co-investment agreement",
    "startDate": "2025-05-20",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "Legacy record carried over from the previous portal seed. (Source: Ecosystem Partners — Sustainability Report 2026)"
  },
  {
    "nameEn": "CUHK-Shenzhen",
    "nameCn": "香港中文大学（深圳）",
    "category": "university",
    "region": "mainland",
    "website": "https://www.cuhk.edu.cn",
    "logoUrl": "https://www.google.com/s2/favicons?domain=cuhk.edu.cn&sz=128",
    "descriptionEn": "Early conversations on GBA cross-border spin-off pipeline.",
    "descriptionCn": "就大湾区跨境衍生企业项目源的早期接触。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Renee Pan"
    ],
    "partnershipType": "Deal flow",
    "startDate": "",
    "stage": "s2_engaged",
    "collabLevel": 2,
    "hallOfFame": 0,
    "notes": "",
    "context": "Legacy record carried over from the previous portal seed. (Source: Ecosystem Partners — Sustainability Report 2026)"
  },
  {
    "nameEn": "BIOHK",
    "nameCn": "香港国际生物科技论坛",
    "category": "research",
    "region": "hongkong",
    "website": "https://www.biohk.org",
    "logoUrl": "https://www.google.com/s2/favicons?domain=biohk.org&sz=128",
    "descriptionEn": "Target partner for life sciences ecosystem collaboration.",
    "descriptionCn": "生命科学生态合作目标伙伴。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Berlin Chen"
    ],
    "partnershipType": "Ecosystem",
    "startDate": "",
    "stage": "s1_new",
    "collabLevel": 1,
    "hallOfFame": 0,
    "notes": "",
    "context": "Legacy record carried over from the previous portal seed. (Source: Ecosystem Partners — Sustainability Report 2026)"
  },
  {
    "nameEn": "OASA",
    "nameCn": "航天科技生态联盟",
    "category": "ecosystem",
    "region": "hongkong",
    "website": "https://www.oasa.org.hk",
    "logoUrl": "https://www.google.com/s2/favicons?domain=oasa.org.hk&sz=128",
    "descriptionEn": "Space tech ecosystem alliance — joint programmes for astropreneurs and orbital economy ventures.",
    "descriptionCn": "航天科技生态联盟——共同支持太空创业者与轨道经济项目。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Fred Li"
    ],
    "partnershipType": "Ecosystem alliance",
    "startDate": "2025-11-01",
    "stage": "s2_engaged",
    "collabLevel": 2,
    "hallOfFame": 0,
    "notes": "Space tech ecosystem partner.",
    "context": "Legacy record carried over from the previous portal seed. (Source: Ecosystem Partners — Sustainability Report 2026)"
  },
  {
    "nameEn": "Cross Capital",
    "nameCn": "Cross Capital",
    "category": "investor",
    "region": "japan",
    "website": "https://crosscapital.ltd",
    "logoUrl": "https://www.google.com/s2/favicons?domain=crosscapital.ltd&sz=128",
    "descriptionEn": "Japan-focused fund-of-funds channelling Japanese corporate LP capital into Southeast Asia; LP in Gobi's Meranti ASEAN Growth Fund II.",
    "descriptionCn": "面向日本的母基金，引导日本企业 LP 资本进入东南亚；Gobi Meranti 东盟成长基金二期 LP。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao",
      "Jong Eon Lee"
    ],
    "partnershipType": "LP — Meranti ASEAN Growth Fund II",
    "startDate": "2024-11-01",
    "stage": "s5_strategic",
    "collabLevel": 5,
    "hallOfFame": 0,
    "notes": "",
    "context": "In November 2024, Gobi Partners and Cross Capital joined forces to supercharge Japanese investment in Southeast Asia's startup ecosystem. Cross Capital, a business-development fund-of-funds connecting Japanese corporate LPs to global startups, invested as an LP in Gobi's Meranti ASEAN Growth Fund II. Note: branded Japan-focused; legal HQ is Cross Capital Pte. Ltd., Singapore. (Source: gobi.vc news, Nov 2024)"
  },
  {
    "nameEn": "JR East TAKANAWA GATEWAY LiSH",
    "nameCn": "JR 东日本高轮门户 LiSH",
    "category": "accelerator",
    "region": "japan",
    "website": "https://www.takanawagateway-lish.com",
    "logoUrl": "https://www.google.com/s2/favicons?domain=takanawagateway-lish.com&sz=128",
    "descriptionEn": "Gobi entered Japan as a Global Network Partner of JR East's TAKANAWA GATEWAY Link Scholars' Hub innovation platform.",
    "descriptionCn": "Gobi 以全球网络伙伴身份加入 JR 东日本高轮门户 Link Scholars' Hub 创新平台，正式进入日本市场。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao",
      "Jong Eon Lee"
    ],
    "partnershipType": "Global Network Partner",
    "startDate": "2025-10-01",
    "stage": "s4_progressive",
    "collabLevel": 4,
    "hallOfFame": 0,
    "notes": "",
    "context": "In 2025 Gobi Partners expanded to Japan by joining TAKANAWA GATEWAY LiSH, JR East's flagship innovation hub, as a Global Network Partner — bridging Southeast Asia's growth with Japan's innovation frontier. (Source: gobi.vc news, 2025)"
  },
  {
    "nameEn": "NTT",
    "nameCn": "日本电信电话株式会社（NTT）",
    "category": "corporate",
    "region": "japan",
    "website": "https://group.ntt",
    "logoUrl": "https://www.google.com/s2/favicons?domain=group.ntt&sz=128",
    "descriptionEn": "Strategic collaboration connecting Gobi's startup network with NTT Group for Japan–Southeast Asia business matching and PoC projects.",
    "descriptionCn": "战略合作——连接 Gobi 创业网络与 NTT 集团，推动日本与东南亚企业对接及概念验证项目。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao",
      "Jong Eon Lee"
    ],
    "partnershipType": "Strategic collaboration",
    "startDate": "2026-07-13",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "In July 2026, Gobi Partners and NTT, Inc. agreed to jointly connect Japanese enterprises with Southeast Asian startups — combining NTT's enterprise network with Gobi's regional portfolio for business matching and proof-of-concept projects. (Source: TechNode Global, Jul 2026)"
  },
  {
    "nameEn": "Tokyo Stock Exchange",
    "nameCn": "东京证券交易所",
    "category": "corporate",
    "region": "japan",
    "website": "https://www.jpx.co.jp",
    "logoUrl": "https://www.google.com/s2/favicons?domain=jpx.co.jp&sz=128",
    "descriptionEn": "Co-hosted the Malaysia–Japan Innovation & Capital Forum with Gobi as part of Gobi's Japan market entry.",
    "descriptionCn": "作为 Gobi 进入日本市场的一部分，与 Gobi 联合主办马来西亚—日本创新与资本论坛。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao"
    ],
    "partnershipType": "Forum co-host",
    "startDate": "2025-10-01",
    "stage": "s2_engaged",
    "collabLevel": 2,
    "hallOfFame": 0,
    "notes": "",
    "context": "Tokyo Stock Exchange (Japan Exchange Group) co-hosted the Malaysia–Japan Innovation & Capital Forum alongside Gobi Partners and JETRO during Gobi's 2025 Japan expansion. (Source: gobi.vc news, 2025)"
  },
  {
    "nameEn": "JETRO",
    "nameCn": "日本贸易振兴机构",
    "category": "government",
    "region": "japan",
    "website": "https://www.jetro.go.jp",
    "logoUrl": "https://www.google.com/s2/favicons?domain=jetro.go.jp&sz=128",
    "descriptionEn": "Co-hosted the Malaysia–Japan Innovation & Capital Forum with Gobi, supporting Japan–ASEAN startup and capital flows.",
    "descriptionCn": "与 Gobi 联合主办马来西亚—日本创新与资本论坛，支持日本与东盟的创业与资本流动。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Thomas G. Tsao"
    ],
    "partnershipType": "Forum co-host",
    "startDate": "2025-10-01",
    "stage": "s2_engaged",
    "collabLevel": 2,
    "hallOfFame": 0,
    "notes": "",
    "context": "JETRO (Japan External Trade Organization) co-hosted the Malaysia–Japan Innovation & Capital Forum alongside Gobi Partners and Tokyo Stock Exchange during Gobi's 2025 Japan expansion. (Source: gobi.vc news, 2025)"
  },
  {
    "nameEn": "SU& Group",
    "nameCn": "SU& 集团",
    "category": "investor",
    "region": "korea",
    "website": "http://www.sunp.co.kr",
    "logoUrl": "https://www.google.com/s2/favicons?domain=sunp.co.kr&sz=128",
    "descriptionEn": "June 2025 strategic agreement to build a joint co-investment fund (target 500B+ won) alongside the launch of Gobi Korea.",
    "descriptionCn": "2025年6月签署战略协议，携手设立联合投资基金（目标逾5000亿韩元），同期成立 Gobi Korea。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Jong Eon Lee",
      "Thomas G. Tsao"
    ],
    "partnershipType": "Joint co-investment fund — Gobi Korea",
    "startDate": "2025-06-18",
    "stage": "s3_agreement",
    "collabLevel": 3,
    "hallOfFame": 0,
    "notes": "",
    "context": "In June 2025, Gobi Partners and Korea's SU& Group signed an agreement to create a joint co-investment fund targeting more than 500 billion won, coinciding with the launch of Gobi Korea. (Source: Chosun Biz, Jun 2025)"
  },
  {
    "nameEn": "Vietnam Ministry of Science and Technology",
    "nameCn": "越南科学技术部",
    "category": "government",
    "region": "vietnam",
    "website": "https://www.most.gov.vn",
    "logoUrl": "https://www.google.com/s2/favicons?domain=most.gov.vn&sz=128",
    "descriptionEn": "Exploratory engagement on joining Vietnam's national venture capital fund initiative (Decree 264/2025).",
    "descriptionCn": "就参与越南国家创业投资基金计划（第264/2025号法令）进行探索性接洽。",
    "contactName": "",
    "contactEmail": "",
    "picNames": [
      "Nhat Minh Phan",
      "Thomas G. Tsao"
    ],
    "partnershipType": "National VC fund — exploratory",
    "startDate": "2026-03-01",
    "stage": "s2_engaged",
    "collabLevel": 2,
    "hallOfFame": 0,
    "notes": "",
    "context": "In March 2026, Gobi Partners expressed interest in joining Vietnam's ~US$19M national venture capital initiative under Decree 264/2025, engaging with the Ministry of Science and Technology. No formal agreement yet — exploratory stage. (Source: TechNode Global, Mar 2026)"
  }
];
