// v4.5 site sync — roles and network refreshed from fred-li.vercel.app (July 2026).
// Applied once via the meta table key "migration_v45_site_sync" in both storages.

// Fred's current role per his site: "Managing Director & Head of University Ventures · Gobi Partners"
export const FRED_TITLE = "Managing Director & Head of University Ventures";

export const V45_NEW_PARTNERS: any[] = [
  {
    nameEn: "The Hong Kong Polytechnic University (PolyU)",
    nameCn: "香港理工大学",
    category: "university",
    region: "hongkong",
    website: "https://www.polyu.edu.hk",
    logoUrl: "https://www.google.com/s2/favicons?domain=polyu.edu.hk&sz=128",
    descriptionEn:
      "Gobi engages PolyU through its university-ventures ecosystem: Fred Li serves as lecturer, panelist, trainer and mentor in PolyU entrepreneurship and technology-transfer programmes — one of six Hong Kong universities where he teaches.",
    descriptionCn:
      "戈壁通过大学创投生态与香港理工大学合作：李冠乐在理大创业与科技成果转化课程中担任讲师、评审与导师，为其授课的六所香港高校之一。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "University ecosystem — teaching & mentorship",
    startDate: "",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "Hong Kong Baptist University (HKBU)",
    nameCn: "香港浸会大学",
    category: "university",
    region: "hongkong",
    website: "https://www.hkbu.edu.hk",
    logoUrl: "https://www.google.com/s2/favicons?domain=hkbu.edu.hk&sz=128",
    descriptionEn:
      "Gobi engages HKBU through its university-ventures ecosystem: Fred Li serves as lecturer, panelist, trainer and mentor in HKBU entrepreneurship programmes — one of six Hong Kong universities where he teaches.",
    descriptionCn:
      "戈壁通过大学创投生态与香港浸会大学合作：李冠乐在浸大创业课程中担任讲师、评审与导师，为其授课的六所香港高校之一。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "University ecosystem — teaching & mentorship",
    startDate: "",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "City University of Hong Kong (CityU)",
    nameCn: "香港城市大学",
    category: "university",
    region: "hongkong",
    website: "https://www.cityu.edu.hk",
    logoUrl: "https://www.google.com/s2/favicons?domain=cityu.edu.hk&sz=128",
    descriptionEn:
      "Gobi engages CityU through its university-ventures ecosystem: Fred Li serves as lecturer, panelist, trainer and mentor in CityU entrepreneurship and innovation programmes — one of six Hong Kong universities where he teaches.",
    descriptionCn:
      "戈壁通过大学创投生态与香港城市大学合作：李冠乐在城大创业与创新课程中担任讲师、评审与导师，为其授课的六所香港高校之一。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "University ecosystem — teaching & mentorship",
    startDate: "",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "NUS BLOCK71",
    nameCn: "新加坡国立大学 BLOCK71",
    category: "accelerator",
    region: "singapore",
    website: "https://block71.co",
    logoUrl: "https://www.google.com/s2/favicons?domain=block71.co&sz=128",
    descriptionEn:
      "BLOCK71 is NUS Enterprise's global startup hub and incubation network. Fred Li mentors founders and joins panels through BLOCK71 ecosystem programmes connecting Singapore and the Greater Bay Area.",
    descriptionCn:
      "BLOCK71 是新加坡国立大学企业机构旗下的全球创业基地与孵化网络。李冠乐通过 BLOCK71 的生态项目担任导师与评审，连接新加坡与大湾区创业生态。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem programme — mentorship",
    startDate: "",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "BIOCHINA",
    nameCn: "BIOCHINA 生物医药产业大会",
    category: "ecosystem",
    region: "mainland",
    website: "",
    logoUrl: "",
    descriptionEn:
      "BIOCHINA is a life-sciences industry conference series in China. Fred Li joins as speaker, panelist and mentor in its biotech ecosystem programmes, alongside BIOHK on the Hong Kong side.",
    descriptionCn:
      "BIOCHINA 为中国生物医药产业大会系列。李冠乐在其生物科技生态活动中担任讲者、评审与导师，与香港的 BIOHK 相呼应。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem programme — speaking & mentorship",
    startDate: "",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "Tencent Education",
    nameCn: "腾讯教育",
    category: "corporate",
    region: "mainland",
    website: "https://edu.tencent.com",
    logoUrl: "https://www.google.com/s2/favicons?domain=edu.tencent.com&sz=128",
    descriptionEn:
      "Tencent's education arm. Fred Li visited Tencent Education in July 2026 (alongside RITS and the GBA National Technology Innovation Center) to explore university-innovation and ecosystem collaboration.",
    descriptionCn:
      "腾讯旗下教育板块。李冠乐于2026年7月到访腾讯教育（同行到访深圳清华研究院与大湾区国创中心），探讨高校创新与生态合作。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem visit — exploratory",
    startDate: "2026-07-01",
    stage: "s1_new",
    collabLevel: 1,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "Research Institute of Tsinghua University in Shenzhen (RITS)",
    nameCn: "深圳清华大学研究院",
    category: "research",
    region: "mainland",
    website: "",
    logoUrl: "",
    descriptionEn:
      "A leading industry-research institute founded by Tsinghua University and the Shenzhen government. Fred Li visited RITS in July 2026 to explore research-commercialisation and university-ventures collaboration.",
    descriptionCn:
      "由清华大学与深圳市政府共建的产学研机构。李冠乐于2026年7月到访深圳清华大学研究院，探讨科研成果转化与大学创投合作。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem visit — exploratory",
    startDate: "2026-07-01",
    stage: "s1_new",
    collabLevel: 1,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "GBA National Technology Innovation Center",
    nameCn: "粤港澳大湾区国家技术创新中心",
    category: "research",
    region: "mainland",
    website: "",
    logoUrl: "",
    descriptionEn:
      "A national technology innovation platform for the Guangdong–Hong Kong–Macao Greater Bay Area. Fred Li visited the GBA National Technology Innovation Center in July 2026 to explore deep-tech commercialisation collaboration.",
    descriptionCn:
      "面向粤港澳大湾区的国家级技术创新平台。李冠乐于2026年7月到访大湾区国创中心，探讨深科技成果转化合作。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem visit — exploratory",
    startDate: "2026-07-01",
    stage: "s1_new",
    collabLevel: 1,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
  {
    nameEn: "LEAP East",
    nameCn: "LEAP East 科技大会",
    category: "ecosystem",
    region: "hongkong",
    website: "",
    logoUrl: "",
    descriptionEn:
      "LEAP East is a premier technology event hosted in Hong Kong. Fred Li speaks at LEAP East in July 2026, representing Gobi's university-ventures and deep-tech investment practice.",
    descriptionCn:
      "LEAP East 为在香港举办的大型科技盛会。李冠乐于2026年7月在 LEAP East 发表演讲，代表戈壁的大学创投与深科技投资业务。",
    contactName: "",
    contactEmail: "",
    picNames: ["Fred Li"],
    partnershipType: "Ecosystem event — speaking engagement",
    startDate: "2026-07-01",
    stage: "s2_engaged",
    collabLevel: 2,
    hallOfFame: 0,
    lpStatus: "na",
    notes: "Source: fred-li.vercel.app (Jul 2026).",
    context: "",
  },
];
